{"0.0.1":{"info":{"author":null,"author_email":null,"bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"datadog-external-dns","package_url":"https://pypi.org/project/datadog-external-dns/","platform":null,"project_url":"https://pypi.org/project/datadog-external-dns/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/datadog-external-dns/0.0.1/","requires_dist":null,"requires_python":null,"summary":null,"version":"0.0.1","yanked":false,"yanked_reason":null},"last_serial":23251725,"urls":[{"comment_text":"","digests":{"blake2b_256":"36b526d192d57b21e04356cc24f6b75f1c2b55ae788ebdad43a3c96c880e791e","md5":"b6446b777d2a4fb36be0a707326e57f6","sha256":"645df24b51db52ddcb8f535027b476bff334f49cb7ae9a4a01520d401eb12c2a"},"downloads":-1,"filename":"datadog_external_dns-0.0.1-py2.py3-none-any.whl","has_sig":false,"md5_digest":"b6446b777d2a4fb36be0a707326e57f6","packagetype":"bdist_wheel","python_version":"py2.py3","requires_python":null,"size":821,"upload_time":"2024-05-17T09:53:39","upload_time_iso_8601":"2024-05-17T09:53:39.439516Z","url":"https://files.pythonhosted.org/packages/36/b5/26d192d57b21e04356cc24f6b75f1c2b55ae788ebdad43a3c96c880e791e/datadog_external_dns-0.0.1-py2.py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}