{"0.0.1":{"info":{"author":"devendrasr","author_email":"devendra@tmdc.io","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://bitbucket.org/rubik_/dataos-sdk-py","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"dataos-sdk-py","package_url":"https://pypi.org/project/dataos-sdk-py/","platform":null,"project_url":"https://pypi.org/project/dataos-sdk-py/","project_urls":{"Bug Tracker":"https://bitbucket.org/rubik_/dataos-soda-py/issues","Homepage":"https://bitbucket.org/rubik_/dataos-soda-py"},"provides_extra":null,"release_url":"https://pypi.org/project/dataos-sdk-py/0.0.1/","requires_dist":["requests ==2.31.0","pydantic ==1.10.9","uplink ==0.9.7"],"requires_python":">=3.7","summary":"Data OS SDK Python","version":"0.0.1","yanked":false,"yanked_reason":null},"last_serial":25811143,"urls":[{"comment_text":"","digests":{"blake2b_256":"f1704e4b0df770aa907270045cc0145929ef0b437f8a942eba30d11b6678458f","md5":"18eab8c60aa40a332b40287c73db5163","sha256":"7e3ce9902e0581ccad4d31b4e213adecdd10911668aec08d5ec6711bf6f343ea"},"downloads":-1,"filename":"dataos_sdk_py-0.0.1-py3-none-any.whl","has_sig":false,"md5_digest":"18eab8c60aa40a332b40287c73db5163","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":67910,"upload_time":"2023-08-24T08:00:33","upload_time_iso_8601":"2023-08-24T08:00:33.946162Z","url":"https://files.pythonhosted.org/packages/f1/70/4e4b0df770aa907270045cc0145929ef0b437f8a942eba30d11b6678458f/dataos_sdk_py-0.0.1-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.2":{"info":{"author":"devendrasr","author_email":"TMDC Labs <labs@tmdc.io>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://bitbucket.org/rubik_/dataos-sdk-py","keywords":null,"license":"Programming Language :: Python :: 3 License :: OSI Approved :: MIT License Operating System :: OS Independent","maintainer":null,"maintainer_email":null,"name":"dataos-sdk-py","package_url":"https://pypi.org/project/dataos-sdk-py/","platform":null,"project_url":"https://pypi.org/project/dataos-sdk-py/","project_urls":{"Homepage":"https://bitbucket.org/rubik_/dataos-sdk-py"},"provides_extra":null,"release_url":"https://pypi.org/project/dataos-sdk-py/0.0.2/","requires_dist":["requests>=2.32.3","pydantic>=2.9.2","uplink>=0.9.7"],"requires_python":">=3.7","summary":"A description of the dataos-sdk-py package","version":"0.0.2","yanked":false,"yanked_reason":null},"last_serial":25811143,"urls":[{"comment_text":"","digests":{"blake2b_256":"500dbccbe17ec9071d783257d5171d07e8b97c8985f190998e8b450197c53637","md5":"7ac49f25f10b4caaf04820ead719da6d","sha256":"82d84230a8b2ab5e15c98c43feac3b41c3c1addafab359661293873c6a72f178"},"downloads":-1,"filename":"dataos_sdk_py-0.0.2-py3-none-any.whl","has_sig":false,"md5_digest":"7ac49f25f10b4caaf04820ead719da6d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":54328,"upload_time":"2024-10-25T13:38:20","upload_time_iso_8601":"2024-10-25T13:38:20.508271Z","url":"https://files.pythonhosted.org/packages/50/0d/bccbe17ec9071d783257d5171d07e8b97c8985f190998e8b450197c53637/dataos_sdk_py-0.0.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"374121a899c6086eea2a41462dda4d0c6ff8c2e8b38e96649c11bd61b695cdfd","md5":"6790464980c24f45c6071c775f070d4d","sha256":"42e3966a26f5dba3a4a6757c0e333e54f18c38831b372d92a0f86b3957bb64c7"},"downloads":-1,"filename":"dataos_sdk_py-0.0.2.tar.gz","has_sig":false,"md5_digest":"6790464980c24f45c6071c775f070d4d","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":36369,"upload_time":"2024-10-25T13:38:22","upload_time_iso_8601":"2024-10-25T13:38:22.448443Z","url":"https://files.pythonhosted.org/packages/37/41/21a899c6086eea2a41462dda4d0c6ff8c2e8b38e96649c11bd61b695cdfd/dataos_sdk_py-0.0.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.3":{"info":{"author":"devendrasr","author_email":"TMDC Labs <labs@tmdc.io>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://bitbucket.org/rubik_/dataos-sdk-py","keywords":null,"license":"Programming Language :: Python :: 3 License :: OSI Approved :: MIT License Operating System :: OS Independent","maintainer":null,"maintainer_email":null,"name":"dataos-sdk-py","package_url":"https://pypi.org/project/dataos-sdk-py/","platform":null,"project_url":"https://pypi.org/project/dataos-sdk-py/","project_urls":{"Homepage":"https://bitbucket.org/rubik_/dataos-sdk-py"},"provides_extra":null,"release_url":"https://pypi.org/project/dataos-sdk-py/0.0.3/","requires_dist":["requests>=2.32.3","pydantic>=2.9.2","uplink>=0.9.7"],"requires_python":">=3.7","summary":"A description of the dataos-sdk-py package","version":"0.0.3","yanked":false,"yanked_reason":null},"last_serial":25811143,"urls":[{"comment_text":"","digests":{"blake2b_256":"65c55fd603b07acdd828de6a0f1450320fadc08d347c5600dbcba7c2abb5bf35","md5":"ed722b5efdb95440c2871f380cb2d89b","sha256":"5fe4e68f372b41b921c08336e776f9f10dac99f398289b62db88ffa07f235740"},"downloads":-1,"filename":"dataos_sdk_py-0.0.3-py3-none-any.whl","has_sig":false,"md5_digest":"ed722b5efdb95440c2871f380cb2d89b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":54335,"upload_time":"2024-11-04T06:57:23","upload_time_iso_8601":"2024-11-04T06:57:23.251116Z","url":"https://files.pythonhosted.org/packages/65/c5/5fd603b07acdd828de6a0f1450320fadc08d347c5600dbcba7c2abb5bf35/dataos_sdk_py-0.0.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"3dcd20591433fd824ca134ebf84def7ff397768d13591ddd6a311ddfec16dff5","md5":"7d5a1caf6b27a1023f955255afb8c128","sha256":"8b388ab986e55737ebe7b1dc4541bbaf224be14ff0bacc28ade5436f42a2b455"},"downloads":-1,"filename":"dataos_sdk_py-0.0.3.tar.gz","has_sig":false,"md5_digest":"7d5a1caf6b27a1023f955255afb8c128","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":35607,"upload_time":"2024-11-04T06:57:25","upload_time_iso_8601":"2024-11-04T06:57:25.387259Z","url":"https://files.pythonhosted.org/packages/3d/cd/20591433fd824ca134ebf84def7ff397768d13591ddd6a311ddfec16dff5/dataos_sdk_py-0.0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}