{"0.1.1":{"info":{"author":"Konstantin Shestakov","author_email":"winmasta@yandex.ru","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3.9","Topic :: Software Development :: Documentation","Topic :: Software Development :: Libraries :: Python Modules","Topic :: Software Development :: Quality Assurance"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/winmasta","keywords":"pylint,exception,lint","license":"MIT","maintainer":"","maintainer_email":"","name":"pylint-exception-var-name-plugin","package_url":"https://pypi.org/project/pylint-exception-var-name-plugin/","platform":"","project_url":"https://pypi.org/project/pylint-exception-var-name-plugin/","project_urls":{"Homepage":"https://github.com/winmasta","Repository":"https://github.com/winmasta"},"provides_extra":null,"release_url":"https://pypi.org/project/pylint-exception-var-name-plugin/0.1.1/","requires_dist":["pylint"],"requires_python":">=3.9,<4.0","summary":"Plugin for pylint which allows to define and check variable name for exception","version":"0.1.1","yanked":false,"yanked_reason":null},"last_serial":17727794,"urls":[{"comment_text":"","digests":{"blake2b_256":"be3a245afcd231bc4d67ec673a4c25d40b39089e99223f8bb857b94bb92c3fe5","md5":"1717fa18b5e08c5df38b9195084c9351","sha256":"db1c58d9a584dca46a63a3af7d45eb591662cad4ba214d7a39b5aaa3ccd22e5e"},"downloads":-1,"filename":"pylint_exception_var_name_plugin-0.1.1-py3-none-any.whl","has_sig":false,"md5_digest":"1717fa18b5e08c5df38b9195084c9351","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9,<4.0","size":4289,"upload_time":"2021-09-03T03:21:58","upload_time_iso_8601":"2021-09-03T03:21:58.040183Z","url":"https://files.pythonhosted.org/packages/be/3a/245afcd231bc4d67ec673a4c25d40b39089e99223f8bb857b94bb92c3fe5/pylint_exception_var_name_plugin-0.1.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"e767ac7d437375cd55bb1dab4bfb72a793b8e14be3c9a3496a6c380154807105","md5":"cfbe4ef070804e9e62e352b35b4c59b2","sha256":"31f24f7cfae314dc2ce5f561e1196b46d62a6b685e07ea8c3caa3a86c9c6f7f6"},"downloads":-1,"filename":"pylint-exception-var-name-plugin-0.1.1.tar.gz","has_sig":false,"md5_digest":"cfbe4ef070804e9e62e352b35b4c59b2","packagetype":"sdist","python_version":"source","requires_python":">=3.9,<4.0","size":2798,"upload_time":"2021-09-03T03:21:56","upload_time_iso_8601":"2021-09-03T03:21:56.417640Z","url":"https://files.pythonhosted.org/packages/e7/67/ac7d437375cd55bb1dab4bfb72a793b8e14be3c9a3496a6c380154807105/pylint-exception-var-name-plugin-0.1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.2":{"info":{"author":"Konstantin Shestakov","author_email":"winmasta@yandex.ru","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3.9","Topic :: Software Development :: Documentation","Topic :: Software Development :: Libraries :: Python Modules","Topic :: Software Development :: Quality Assurance"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/winmasta","keywords":"pylint,exception,lint","license":"MIT","maintainer":"","maintainer_email":"","name":"pylint-exception-var-name-plugin","package_url":"https://pypi.org/project/pylint-exception-var-name-plugin/","platform":"","project_url":"https://pypi.org/project/pylint-exception-var-name-plugin/","project_urls":{"Homepage":"https://github.com/winmasta","Repository":"https://github.com/winmasta"},"provides_extra":null,"release_url":"https://pypi.org/project/pylint-exception-var-name-plugin/0.1.2/","requires_dist":["pylint"],"requires_python":">=3.9,<4.0","summary":"Plugin for pylint which allows to define and check variable name for exception","version":"0.1.2","yanked":false,"yanked_reason":null},"last_serial":17727794,"urls":[{"comment_text":"","digests":{"blake2b_256":"dad6cf43e5815a9bb18aae893bf4b734f7a1ae386690986d5a270b42773f688b","md5":"1b68fa7f28a6ebb4c9cc30ba69caca9c","sha256":"8d4ee51b9e846c428a7b71bf6d14cb33b3c4bbd60359d8d6deb984e3e1fc4ff8"},"downloads":-1,"filename":"pylint_exception_var_name_plugin-0.1.2-py3-none-any.whl","has_sig":false,"md5_digest":"1b68fa7f28a6ebb4c9cc30ba69caca9c","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9,<4.0","size":4293,"upload_time":"2021-09-11T10:06:58","upload_time_iso_8601":"2021-09-11T10:06:58.360497Z","url":"https://files.pythonhosted.org/packages/da/d6/cf43e5815a9bb18aae893bf4b734f7a1ae386690986d5a270b42773f688b/pylint_exception_var_name_plugin-0.1.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"d200efbafc0611ff6e79f8bf1acf7d81aeb241a8561b596c180c7f515c5aa16e","md5":"58e0cbb131fb044a1cb3276b7f75cad3","sha256":"be0c59d78812e0660e31d586efa5b1700bd8194c9d0c962d8a07ab50e9ed152f"},"downloads":-1,"filename":"pylint-exception-var-name-plugin-0.1.2.tar.gz","has_sig":false,"md5_digest":"58e0cbb131fb044a1cb3276b7f75cad3","packagetype":"sdist","python_version":"source","requires_python":">=3.9,<4.0","size":2736,"upload_time":"2021-09-11T10:06:56","upload_time_iso_8601":"2021-09-11T10:06:56.736012Z","url":"https://files.pythonhosted.org/packages/d2/00/efbafc0611ff6e79f8bf1acf7d81aeb241a8561b596c180c7f515c5aa16e/pylint-exception-var-name-plugin-0.1.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.3":{"info":{"author":"Konstantin Shestakov","author_email":"winmasta@yandex.ru","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3.10","Programming Language :: Python :: 3.11","Programming Language :: Python :: 3.9","Topic :: Software Development :: Documentation","Topic :: Software Development :: Libraries :: Python Modules","Topic :: Software Development :: Quality Assurance"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/winmasta","keywords":"pylint,exception,lint","license":"MIT","maintainer":"","maintainer_email":"","name":"pylint-exception-var-name-plugin","package_url":"https://pypi.org/project/pylint-exception-var-name-plugin/","platform":null,"project_url":"https://pypi.org/project/pylint-exception-var-name-plugin/","project_urls":{"Homepage":"https://github.com/winmasta","Repository":"https://github.com/winmasta"},"provides_extra":null,"release_url":"https://pypi.org/project/pylint-exception-var-name-plugin/0.1.3/","requires_dist":["pylint"],"requires_python":">=3.9,<4.0","summary":"Plugin for pylint which allows to define and check variable name for exception","version":"0.1.3","yanked":false,"yanked_reason":null},"last_serial":17727794,"urls":[{"comment_text":"","digests":{"blake2b_256":"325fe15e90864dd5b20340881038907f2ae0693eb35fcb5aa876c09f27610d8b","md5":"6f404c22bee8af22fc5a6204309e2059","sha256":"a371ec4a923b41662efed8cf1c71f8ade898929ddaf600763670f9fc2e6fe442"},"downloads":-1,"filename":"pylint_exception_var_name_plugin-0.1.3-py3-none-any.whl","has_sig":false,"md5_digest":"6f404c22bee8af22fc5a6204309e2059","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.9,<4.0","size":4241,"upload_time":"2023-04-16T14:44:06","upload_time_iso_8601":"2023-04-16T14:44:06.197935Z","url":"https://files.pythonhosted.org/packages/32/5f/e15e90864dd5b20340881038907f2ae0693eb35fcb5aa876c09f27610d8b/pylint_exception_var_name_plugin-0.1.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"119c86aa07b51d06ab23149db583ce6adb4a8baaf504199f899c6df3af59ad8e","md5":"ad8e5567d7629c3e17e93ed047a0eeeb","sha256":"d415464835a13e4d8bd1fd4a29f88e019692a292b5efafa19be60867865498de"},"downloads":-1,"filename":"pylint_exception_var_name_plugin-0.1.3.tar.gz","has_sig":false,"md5_digest":"ad8e5567d7629c3e17e93ed047a0eeeb","packagetype":"sdist","python_version":"source","requires_python":">=3.9,<4.0","size":2539,"upload_time":"2023-04-16T14:44:07","upload_time_iso_8601":"2023-04-16T14:44:07.738974Z","url":"https://files.pythonhosted.org/packages/11/9c/86aa07b51d06ab23149db583ce6adb4a8baaf504199f899c6df3af59ad8e/pylint_exception_var_name_plugin-0.1.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}