{"0.0.3":{"info":{"author":null,"author_email":"Jakob Unterwurzacher <jakobunt@gmail.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3.8"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"unhandled_exit","package_url":"https://pypi.org/project/unhandled_exit/","platform":null,"project_url":"https://pypi.org/project/unhandled_exit/","project_urls":{"Bug Tracker":"https://github.com/rfjakob/unhandled_exit/issues","Homepage":"https://github.com/rfjakob/unhandled_exit"},"provides_extra":null,"release_url":"https://pypi.org/project/unhandled_exit/0.0.3/","requires_dist":null,"requires_python":">=3.8","summary":"Exit the whole process if any thread throws an unhandled exception","version":"0.0.3","yanked":false,"yanked_reason":null},"last_serial":15500814,"urls":[{"comment_text":null,"digests":{"blake2b_256":"a3ac805673cd4b55dbf66bfed5ef7ba97a619a0ef097b00fb722d82bcc9959c5","md5":"ba8f67d08c3db6fcd7d6ccacac43090f","sha256":"8b5e6bcb54d818398b36196e9b5bfa18175438edc6ff3c4550e6ac7f3ac089ca"},"downloads":-1,"filename":"unhandled_exit-0.0.3-py3-none-any.whl","has_sig":false,"md5_digest":"ba8f67d08c3db6fcd7d6ccacac43090f","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":3673,"upload_time":"2022-10-11T19:37:45","upload_time_iso_8601":"2022-10-11T19:37:45.527047Z","url":"https://files.pythonhosted.org/packages/a3/ac/805673cd4b55dbf66bfed5ef7ba97a619a0ef097b00fb722d82bcc9959c5/unhandled_exit-0.0.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":null,"digests":{"blake2b_256":"6f0c48438a878d806f5cf598dd2ad6c8cacf7dbec0cdc7fc70744a9cb5a9968b","md5":"c67fe215efb698f6aab5d83e0ced9cec","sha256":"cd578df54ef4e446cd48cf00a7281534695d5c8804c41f79a87d4187d6fbc521"},"downloads":-1,"filename":"unhandled_exit-0.0.3.tar.gz","has_sig":false,"md5_digest":"c67fe215efb698f6aab5d83e0ced9cec","packagetype":"sdist","python_version":"source","requires_python":">=3.8","size":3266,"upload_time":"2022-10-11T19:37:48","upload_time_iso_8601":"2022-10-11T19:37:48.327916Z","url":"https://files.pythonhosted.org/packages/6f/0c/48438a878d806f5cf598dd2ad6c8cacf7dbec0cdc7fc70744a9cb5a9968b/unhandled_exit-0.0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.0.0":{"info":{"author":null,"author_email":"Jakob Unterwurzacher <jakobunt@gmail.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3.8"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"unhandled_exit","package_url":"https://pypi.org/project/unhandled_exit/","platform":null,"project_url":"https://pypi.org/project/unhandled_exit/","project_urls":{"Bug Tracker":"https://github.com/rfjakob/unhandled_exit/issues","Source Code":"https://github.com/rfjakob/unhandled_exit"},"provides_extra":null,"release_url":"https://pypi.org/project/unhandled_exit/1.0.0/","requires_dist":null,"requires_python":">=3.8","summary":"Exit the whole process if any thread throws an unhandled exception","version":"1.0.0","yanked":false,"yanked_reason":null},"last_serial":15500814,"urls":[{"comment_text":null,"digests":{"blake2b_256":"8af4c900d50aee7eead3170e0dd50a192d19f5df8ca7e0ece59b9f73a858215c","md5":"cbc34ccc980555a85273bb560702fdd3","sha256":"100df644ab9de07c7a33b4bd6553dcc14f42cdbf5de9a2cdb7e0dbe1c99850d8"},"downloads":-1,"filename":"unhandled_exit-1.0.0-py3-none-any.whl","has_sig":false,"md5_digest":"cbc34ccc980555a85273bb560702fdd3","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":4086,"upload_time":"2022-10-23T12:31:46","upload_time_iso_8601":"2022-10-23T12:31:46.452992Z","url":"https://files.pythonhosted.org/packages/8a/f4/c900d50aee7eead3170e0dd50a192d19f5df8ca7e0ece59b9f73a858215c/unhandled_exit-1.0.0-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":null,"digests":{"blake2b_256":"5824f80ef91968bdbb2398774646e7fada0e71cddd07d006c612f86e62bdac5c","md5":"f4353bc550a04696d7246dda70a43fd5","sha256":"935a4e752e98b2d76a0afba6b47c7a692231a08158a60e90df559985596f22fb"},"downloads":-1,"filename":"unhandled_exit-1.0.0.tar.gz","has_sig":false,"md5_digest":"f4353bc550a04696d7246dda70a43fd5","packagetype":"sdist","python_version":"source","requires_python":">=3.8","size":4500,"upload_time":"2022-10-23T12:31:44","upload_time_iso_8601":"2022-10-23T12:31:44.010167Z","url":"https://files.pythonhosted.org/packages/58/24/f80ef91968bdbb2398774646e7fada0e71cddd07d006c612f86e62bdac5c/unhandled_exit-1.0.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"1.0.0rc1":{"info":{"author":null,"author_email":"Jakob Unterwurzacher <jakobunt@gmail.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3","Programming Language :: Python :: 3.8"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"unhandled_exit","package_url":"https://pypi.org/project/unhandled_exit/","platform":null,"project_url":"https://pypi.org/project/unhandled_exit/","project_urls":{"Bug Tracker":"https://github.com/rfjakob/unhandled_exit/issues","Source Code":"https://github.com/rfjakob/unhandled_exit"},"provides_extra":null,"release_url":"https://pypi.org/project/unhandled_exit/1.0.0rc1/","requires_dist":null,"requires_python":">=3.8","summary":"Exit the whole process if any thread throws an unhandled exception","version":"1.0.0rc1","yanked":false,"yanked_reason":null},"last_serial":15500814,"urls":[{"comment_text":null,"digests":{"blake2b_256":"9dedb1d7a072f2147a6caa7a5f1566db5a8e290f366ed92ef0af4d54fbb62690","md5":"53254d568b3b04a95fb8f5391176a3c1","sha256":"dae4b10c2840aff7f0e78cb84ffdc8090f01a70155da5c7de21f66a23fe0f9fa"},"downloads":-1,"filename":"unhandled_exit-1.0.0rc1-py3-none-any.whl","has_sig":false,"md5_digest":"53254d568b3b04a95fb8f5391176a3c1","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":4114,"upload_time":"2022-10-23T12:27:25","upload_time_iso_8601":"2022-10-23T12:27:25.983890Z","url":"https://files.pythonhosted.org/packages/9d/ed/b1d7a072f2147a6caa7a5f1566db5a8e290f366ed92ef0af4d54fbb62690/unhandled_exit-1.0.0rc1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":null,"digests":{"blake2b_256":"ae259cdd1bf34820da2728357242359f6b39791ece8ca805337497eab75e6738","md5":"b49e75f038434ac07a27448fc718b8f6","sha256":"81cc002c0b2fa660d8e01132d6c550c7c21ae9a74e83ed3ee183d261f17307cb"},"downloads":-1,"filename":"unhandled_exit-1.0.0rc1.tar.gz","has_sig":false,"md5_digest":"b49e75f038434ac07a27448fc718b8f6","packagetype":"sdist","python_version":"source","requires_python":">=3.8","size":4506,"upload_time":"2022-10-23T12:27:28","upload_time_iso_8601":"2022-10-23T12:27:28.175115Z","url":"https://files.pythonhosted.org/packages/ae/25/9cdd1bf34820da2728357242359f6b39791ece8ca805337497eab75e6738/unhandled_exit-1.0.0rc1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}