{"0.0.1":{"info":{"author":"01270","author_email":"yazanemails@gmail.com","bugtrack_url":null,"classifiers":["Development Status :: 1 - Planning","Intended Audience :: Developers","Operating System :: MacOS :: MacOS X","Operating System :: Microsoft :: Windows","Operating System :: Unix","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/TeaByte/GoodError/","keywords":"exception handling,GPT-3,Python library","license":"","maintainer":"","maintainer_email":"","name":"gooderror","package_url":"https://pypi.org/project/gooderror/","platform":null,"project_url":"https://pypi.org/project/gooderror/","project_urls":{"Bug Reports":"https://github.com/TeaByte/GoodError/issues","Documentation":"https://github.com/TeaByte/GoodError/","Homepage":"https://github.com/TeaByte/GoodError/","Source":"https://github.com/TeaByte/GoodError/"},"provides_extra":null,"release_url":"https://pypi.org/project/gooderror/0.0.1/","requires_dist":["openai"],"requires_python":"","summary":"GoodError is a Python library that enhances exception handling, including integration with GPT-3 for additional context.","version":"0.0.1","yanked":false,"yanked_reason":null},"last_serial":19736971,"urls":[{"comment_text":"","digests":{"blake2b_256":"16d3a5737225245728f2d104c081f105e32623ce411c80b267c7565cf4661f85","md5":"a327293993904af86acc6a42820c6bcf","sha256":"3dd7383914943d04f55dd2bd904dd7c16939a9e5f09a68e946235f4d2874ab6c"},"downloads":-1,"filename":"gooderror-0.0.1-py3-none-any.whl","has_sig":false,"md5_digest":"a327293993904af86acc6a42820c6bcf","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3317,"upload_time":"2023-09-13T20:24:28","upload_time_iso_8601":"2023-09-13T20:24:28.486547Z","url":"https://files.pythonhosted.org/packages/16/d3/a5737225245728f2d104c081f105e32623ce411c80b267c7565cf4661f85/gooderror-0.0.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"d187fc597089b6f0e380a164b33d59818c5adee64cb9c351e27f6db3e077f10d","md5":"e3844e7c9204310c39f34ed80c3809be","sha256":"abef7913c3c0297aba5067f266076d8a59be13be0bbb61e6aa66481d306a9c53"},"downloads":-1,"filename":"gooderror-0.0.1.tar.gz","has_sig":false,"md5_digest":"e3844e7c9204310c39f34ed80c3809be","packagetype":"sdist","python_version":"source","requires_python":null,"size":3654,"upload_time":"2023-09-13T20:24:30","upload_time_iso_8601":"2023-09-13T20:24:30.623001Z","url":"https://files.pythonhosted.org/packages/d1/87/fc597089b6f0e380a164b33d59818c5adee64cb9c351e27f6db3e077f10d/gooderror-0.0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.2":{"info":{"author":"01270","author_email":"yazanemails@gmail.com","bugtrack_url":null,"classifiers":["Development Status :: 1 - Planning","Intended Audience :: Developers","Operating System :: MacOS :: MacOS X","Operating System :: Microsoft :: Windows","Operating System :: Unix","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/TeaByte/GoodError/","keywords":"exception handling,GPT-3,Python library","license":"","maintainer":"","maintainer_email":"","name":"gooderror","package_url":"https://pypi.org/project/gooderror/","platform":null,"project_url":"https://pypi.org/project/gooderror/","project_urls":{"Bug Reports":"https://github.com/TeaByte/GoodError/issues","Documentation":"https://github.com/TeaByte/GoodError/","Homepage":"https://github.com/TeaByte/GoodError/","Source":"https://github.com/TeaByte/GoodError/"},"provides_extra":null,"release_url":"https://pypi.org/project/gooderror/0.0.2/","requires_dist":["openai"],"requires_python":"","summary":"GoodError is a Python library that enhances exception handling, including integration with GPT-3 for additional context.","version":"0.0.2","yanked":false,"yanked_reason":null},"last_serial":19736971,"urls":[{"comment_text":"","digests":{"blake2b_256":"7e7cd7b3735fe446e4991de83ae5e139e53ab34f08f65f1a29317b58fb9b79ae","md5":"c75a09dc1deb9dc014a45236634199ce","sha256":"97ef64f2839f10ecbd15bf7612b4fd4d9d172e27c3ff5e95e6c925d1354fc4de"},"downloads":-1,"filename":"gooderror-0.0.2-py3-none-any.whl","has_sig":false,"md5_digest":"c75a09dc1deb9dc014a45236634199ce","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3316,"upload_time":"2023-09-13T20:35:57","upload_time_iso_8601":"2023-09-13T20:35:57.001736Z","url":"https://files.pythonhosted.org/packages/7e/7c/d7b3735fe446e4991de83ae5e139e53ab34f08f65f1a29317b58fb9b79ae/gooderror-0.0.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"421cfa03b0bd02b703a47a441ebfdab1648aaf54ac78f0ce5372b69049938d6c","md5":"cca7efdf585e0856ec1ccbf2ce3fe21b","sha256":"68679140347b82cb93a2fd3e48bcd98621f76f1da90a3ff7f30117fb43596ff9"},"downloads":-1,"filename":"gooderror-0.0.2.tar.gz","has_sig":false,"md5_digest":"cca7efdf585e0856ec1ccbf2ce3fe21b","packagetype":"sdist","python_version":"source","requires_python":null,"size":3671,"upload_time":"2023-09-13T20:35:58","upload_time_iso_8601":"2023-09-13T20:35:58.372768Z","url":"https://files.pythonhosted.org/packages/42/1c/fa03b0bd02b703a47a441ebfdab1648aaf54ac78f0ce5372b69049938d6c/gooderror-0.0.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.3":{"info":{"author":"01270","author_email":"yazanemails@gmail.com","bugtrack_url":null,"classifiers":["Development Status :: 1 - Planning","Intended Audience :: Developers","Operating System :: MacOS :: MacOS X","Operating System :: Microsoft :: Windows","Operating System :: Unix","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/TeaByte/GoodError/","keywords":"exception handling,GPT-3,Python library","license":"","maintainer":"","maintainer_email":"","name":"gooderror","package_url":"https://pypi.org/project/gooderror/","platform":null,"project_url":"https://pypi.org/project/gooderror/","project_urls":{"Bug Reports":"https://github.com/TeaByte/GoodError/issues","Documentation":"https://github.com/TeaByte/GoodError/","Homepage":"https://github.com/TeaByte/GoodError/","Source":"https://github.com/TeaByte/GoodError/"},"provides_extra":null,"release_url":"https://pypi.org/project/gooderror/0.0.3/","requires_dist":["openai"],"requires_python":"","summary":"GoodError is a Python library that enhances exception handling, including integration with GPT-3 for additional context.","version":"0.0.3","yanked":false,"yanked_reason":null},"last_serial":19736971,"urls":[{"comment_text":"","digests":{"blake2b_256":"9b464b9dad3247fc9520a775ba7e0d9d651b48fb3842bd39f9c2c3b3d90b083f","md5":"4a19bc286e0661b5ec472a8f92376ac5","sha256":"ba47e5abd2d7066ad3654a0b2721c1f2bd71151155c8490ef8ca22dae2d6c83e"},"downloads":-1,"filename":"gooderror-0.0.3-py3-none-any.whl","has_sig":false,"md5_digest":"4a19bc286e0661b5ec472a8f92376ac5","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3348,"upload_time":"2023-09-13T21:36:32","upload_time_iso_8601":"2023-09-13T21:36:32.295855Z","url":"https://files.pythonhosted.org/packages/9b/46/4b9dad3247fc9520a775ba7e0d9d651b48fb3842bd39f9c2c3b3d90b083f/gooderror-0.0.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"7b968a4c15cf5244efc22f341faa755f714ab18bb46f44c09e90e08e6490a5bd","md5":"a8e87cc20289d78ece7b45167d144673","sha256":"21d4c1b12cf4c5f9db741ca894b52790b901341783df49b92213a894e2dea1e7"},"downloads":-1,"filename":"gooderror-0.0.3.tar.gz","has_sig":false,"md5_digest":"a8e87cc20289d78ece7b45167d144673","packagetype":"sdist","python_version":"source","requires_python":null,"size":3705,"upload_time":"2023-09-13T21:36:33","upload_time_iso_8601":"2023-09-13T21:36:33.454761Z","url":"https://files.pythonhosted.org/packages/7b/96/8a4c15cf5244efc22f341faa755f714ab18bb46f44c09e90e08e6490a5bd/gooderror-0.0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}