{"0.1":{"info":{"author":"Your Name","author_email":"your.email@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.1/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.1","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"e02d8430aab920220979cbe75a44d4e235f90cac82218ccf14cacfb76b48d1cf","md5":"d00ca33f78235b5ca8c72420fc061e8e","sha256":"0cd1a6e6e29004ca5507a362656b5ce0f9dc5d1c3e47f65555b65674fc6ca70f"},"downloads":-1,"filename":"logging_error_custom-0.1-py3-none-any.whl","has_sig":false,"md5_digest":"d00ca33f78235b5ca8c72420fc061e8e","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":2452,"upload_time":"2024-08-11T09:07:04","upload_time_iso_8601":"2024-08-11T09:07:04.341413Z","url":"https://files.pythonhosted.org/packages/e0/2d/8430aab920220979cbe75a44d4e235f90cac82218ccf14cacfb76b48d1cf/logging_error_custom-0.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"8078644c1d8cd4cfaeb15a546a6033b68ed4f049687f7e245b94475916878cf6","md5":"40dc31d4272088ac44fd510daaa7d906","sha256":"212c0661cc2b8beb045c1ec9a64e8c3897fb7b6717f9bb742fc98aebe9f17194"},"downloads":-1,"filename":"logging_error_custom-0.1.tar.gz","has_sig":false,"md5_digest":"40dc31d4272088ac44fd510daaa7d906","packagetype":"sdist","python_version":"source","requires_python":null,"size":2745,"upload_time":"2024-08-11T09:07:06","upload_time_iso_8601":"2024-08-11T09:07:06.225373Z","url":"https://files.pythonhosted.org/packages/80/78/644c1d8cd4cfaeb15a546a6033b68ed4f049687f7e245b94475916878cf6/logging_error_custom-0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.10":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.10/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.10","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"bdde3590e9722ea374df6aef3db9f2e0f1cc4303aa870ebf8473b1ed5de37442","md5":"9f202e84382b2c5e503c9abe01178578","sha256":"f1fc61c13d1ad0486792722d9fec5d7a6363ded8f5cc80377178d25084386fd4"},"downloads":-1,"filename":"logging_error_custom-0.10-py3-none-any.whl","has_sig":false,"md5_digest":"9f202e84382b2c5e503c9abe01178578","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3156,"upload_time":"2024-08-14T07:23:01","upload_time_iso_8601":"2024-08-14T07:23:01.246629Z","url":"https://files.pythonhosted.org/packages/bd/de/3590e9722ea374df6aef3db9f2e0f1cc4303aa870ebf8473b1ed5de37442/logging_error_custom-0.10-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"55e1e52763fdb249ba1532b8278bdd05ce7efb91659b2241644e4c82ac5637fa","md5":"cb50ea20306ac8f487f4c986916a3dd1","sha256":"602d170b7fd6abf763301af8252ac05c61dc3b3f36db37ea3b76c4b41934f353"},"downloads":-1,"filename":"logging_error_custom-0.10.tar.gz","has_sig":false,"md5_digest":"cb50ea20306ac8f487f4c986916a3dd1","packagetype":"sdist","python_version":"source","requires_python":null,"size":2647,"upload_time":"2024-08-14T07:23:02","upload_time_iso_8601":"2024-08-14T07:23:02.693694Z","url":"https://files.pythonhosted.org/packages/55/e1/e52763fdb249ba1532b8278bdd05ce7efb91659b2241644e4c82ac5637fa/logging_error_custom-0.10.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.12":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.12/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.12","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"11efbe885712183a1af953a6d3b38c8b9cf121fd7a8e606339eceaf4f392168f","md5":"3c3f5a076a86fcceca54436ddc1579da","sha256":"c1a4ccbf554eca0ae51ac5c492aa18dba458dbb51b94e9df763b967ecf57a782"},"downloads":-1,"filename":"logging_error_custom-0.12-py3-none-any.whl","has_sig":false,"md5_digest":"3c3f5a076a86fcceca54436ddc1579da","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3233,"upload_time":"2024-08-20T07:09:15","upload_time_iso_8601":"2024-08-20T07:09:15.466360Z","url":"https://files.pythonhosted.org/packages/11/ef/be885712183a1af953a6d3b38c8b9cf121fd7a8e606339eceaf4f392168f/logging_error_custom-0.12-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"a983dcc26e69fe11f3dfde15fd08a5a3ffe33246b71fe95e0ba1da5e3abdb6d7","md5":"618e5232f5637a079c8a790417baf21d","sha256":"a82b6f93d959365a3881bdce971ee551a83f5a81393a47b55f768ab2795ea557"},"downloads":-1,"filename":"logging_error_custom-0.12.tar.gz","has_sig":false,"md5_digest":"618e5232f5637a079c8a790417baf21d","packagetype":"sdist","python_version":"source","requires_python":null,"size":3228,"upload_time":"2024-08-20T07:09:16","upload_time_iso_8601":"2024-08-20T07:09:16.550892Z","url":"https://files.pythonhosted.org/packages/a9/83/dcc26e69fe11f3dfde15fd08a5a3ffe33246b71fe95e0ba1da5e3abdb6d7/logging_error_custom-0.12.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.13":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.13/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.13","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"1d21ec87a2858154357f21a8896629bb76dabe7d0ac05b55d01c62086e59d3f2","md5":"25fee343209c70782746afec57a54b09","sha256":"06aba6a3493896b511c9f80ed88171dddd43b9a2269ed14dd4266ba098cf2744"},"downloads":-1,"filename":"logging_error_custom-0.13-py3-none-any.whl","has_sig":false,"md5_digest":"25fee343209c70782746afec57a54b09","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3230,"upload_time":"2024-08-20T07:14:01","upload_time_iso_8601":"2024-08-20T07:14:01.432837Z","url":"https://files.pythonhosted.org/packages/1d/21/ec87a2858154357f21a8896629bb76dabe7d0ac05b55d01c62086e59d3f2/logging_error_custom-0.13-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"a3d4cf93c3f17c8ecc48a61fbf538b64fc62d03bc9b960a7ff42e13928aead69","md5":"366e5def9585c7c66ff1d0330f5921a6","sha256":"ff0be838216ff30df563cb64588cafa02cd11c35a9e690963d1354984f61a808"},"downloads":-1,"filename":"logging_error_custom-0.13.tar.gz","has_sig":false,"md5_digest":"366e5def9585c7c66ff1d0330f5921a6","packagetype":"sdist","python_version":"source","requires_python":null,"size":2762,"upload_time":"2024-08-20T07:14:02","upload_time_iso_8601":"2024-08-20T07:14:02.502181Z","url":"https://files.pythonhosted.org/packages/a3/d4/cf93c3f17c8ecc48a61fbf538b64fc62d03bc9b960a7ff42e13928aead69/logging_error_custom-0.13.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3":{"info":{"author":"Your Name","author_email":"your.email@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.3/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.3","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"de2cc417f03e5bcb77587c1ef9a0d0de6768497aeeb33c3afc0a21cd0936cc67","md5":"df870bf2ddc5431439459f38e9ad1ed2","sha256":"5203019c10d8b6ae32c690f72535423b4d766393ec8a18efe6a8912b12ec2d14"},"downloads":-1,"filename":"logging_error_custom-0.3-py3-none-any.whl","has_sig":false,"md5_digest":"df870bf2ddc5431439459f38e9ad1ed2","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":2446,"upload_time":"2024-08-11T10:36:43","upload_time_iso_8601":"2024-08-11T10:36:43.328104Z","url":"https://files.pythonhosted.org/packages/de/2c/c417f03e5bcb77587c1ef9a0d0de6768497aeeb33c3afc0a21cd0936cc67/logging_error_custom-0.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"02a17c51efe26496199553f8699421aa345f3123b03c240942e6f689f083ee97","md5":"0b5f91a87cd466582a6b12ec4263c39a","sha256":"f04d261c2ce1e34071a04485906cc0c8f5ba3460ee265ee398a64521d726b108"},"downloads":-1,"filename":"logging_error_custom-0.3.tar.gz","has_sig":false,"md5_digest":"0b5f91a87cd466582a6b12ec4263c39a","packagetype":"sdist","python_version":"source","requires_python":null,"size":1950,"upload_time":"2024-08-11T10:36:44","upload_time_iso_8601":"2024-08-11T10:36:44.790467Z","url":"https://files.pythonhosted.org/packages/02/a1/7c51efe26496199553f8699421aa345f3123b03c240942e6f689f083ee97/logging_error_custom-0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.4":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.4/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.4","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"958a0dbf7ec212bdf8148105b1bb2c09dd6b836b79572b4f481da9f563b889fe","md5":"f6dc4bbc0727fd98c175ac3469ef0a00","sha256":"a96c643c6cc3e1cefebcc066d7b7ce166082a9628dd4bb4582fe4884c5743545"},"downloads":-1,"filename":"logging_error_custom-0.4-py3-none-any.whl","has_sig":false,"md5_digest":"f6dc4bbc0727fd98c175ac3469ef0a00","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":2683,"upload_time":"2024-08-13T09:30:53","upload_time_iso_8601":"2024-08-13T09:30:53.247366Z","url":"https://files.pythonhosted.org/packages/95/8a/0dbf7ec212bdf8148105b1bb2c09dd6b836b79572b4f481da9f563b889fe/logging_error_custom-0.4-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"16328d3eed68ec6a07d1fd3c35461b35efc0849dadc3a1b74a7d6a252798e3b1","md5":"368ffa12bb398381f1d413d2b291686a","sha256":"05aac158f7dc82b4918f9837bfee4adfd3952dc1a0cb9becba2f3507e0cfbf11"},"downloads":-1,"filename":"logging_error_custom-0.4.tar.gz","has_sig":false,"md5_digest":"368ffa12bb398381f1d413d2b291686a","packagetype":"sdist","python_version":"source","requires_python":null,"size":2178,"upload_time":"2024-08-13T09:30:54","upload_time_iso_8601":"2024-08-13T09:30:54.642465Z","url":"https://files.pythonhosted.org/packages/16/32/8d3eed68ec6a07d1fd3c35461b35efc0849dadc3a1b74a7d6a252798e3b1/logging_error_custom-0.4.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.5":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.5/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.5","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"8f2b740600f9a445466371da2c1098f23580480e20da4104b35537fe378c9080","md5":"705d00ffaa9d784a9a78e5af6ae482c2","sha256":"1e212356cc705a085703c604b21be21e0bf439117027a71f9236dbb557eb222e"},"downloads":-1,"filename":"logging_error_custom-0.5-py3-none-any.whl","has_sig":false,"md5_digest":"705d00ffaa9d784a9a78e5af6ae482c2","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":2670,"upload_time":"2024-08-13T14:42:41","upload_time_iso_8601":"2024-08-13T14:42:41.697585Z","url":"https://files.pythonhosted.org/packages/8f/2b/740600f9a445466371da2c1098f23580480e20da4104b35537fe378c9080/logging_error_custom-0.5-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"8b63b40fdd177cfc11a99e2bf68b140b2a736458a2863c6ca339acf42f4a2770","md5":"fbb5d5aa49014b4618f85b0e7fd4aaeb","sha256":"f8be969fef388c58e55f5898566b55527d8e1fb5b6bebfdd317ad28b30aa4340"},"downloads":-1,"filename":"logging_error_custom-0.5.tar.gz","has_sig":false,"md5_digest":"fbb5d5aa49014b4618f85b0e7fd4aaeb","packagetype":"sdist","python_version":"source","requires_python":null,"size":2150,"upload_time":"2024-08-13T14:42:42","upload_time_iso_8601":"2024-08-13T14:42:42.939360Z","url":"https://files.pythonhosted.org/packages/8b/63/b40fdd177cfc11a99e2bf68b140b2a736458a2863c6ca339acf42f4a2770/logging_error_custom-0.5.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.6":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.6/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.6","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"f112b2336a9534386419499e0f20b7c2e8317f734cf7330376c4b026ecd29ead","md5":"e89d5bc773855bd84bd04b824da54356","sha256":"bae023928030a36e554556a89c2e82ac96716f7947bd51e8832193d279982f55"},"downloads":-1,"filename":"logging_error_custom-0.6-py3-none-any.whl","has_sig":false,"md5_digest":"e89d5bc773855bd84bd04b824da54356","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":2683,"upload_time":"2024-08-13T14:51:11","upload_time_iso_8601":"2024-08-13T14:51:11.115889Z","url":"https://files.pythonhosted.org/packages/f1/12/b2336a9534386419499e0f20b7c2e8317f734cf7330376c4b026ecd29ead/logging_error_custom-0.6-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"a73ce3eefcfc050600ae6916d6d3a8c5d96a0593dd731fd5620e2693a4f423c0","md5":"d165b1196799ecde8a6a219b0eb82a2a","sha256":"0d06ab9fd783c74033b4f5ec7179453703f95287ddc653e82916dc19c90d55c1"},"downloads":-1,"filename":"logging_error_custom-0.6.tar.gz","has_sig":false,"md5_digest":"d165b1196799ecde8a6a219b0eb82a2a","packagetype":"sdist","python_version":"source","requires_python":null,"size":2145,"upload_time":"2024-08-13T14:51:12","upload_time_iso_8601":"2024-08-13T14:51:12.831505Z","url":"https://files.pythonhosted.org/packages/a7/3c/e3eefcfc050600ae6916d6d3a8c5d96a0593dd731fd5620e2693a4f423c0/logging_error_custom-0.6.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.7":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.7/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.7","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"ee6807fba897b22a6ab342563ac117787a8e257487f22f86f656fda212b01921","md5":"b72f06c83224704e2c8bb667bb2de721","sha256":"f656f553961974f144656e7c963fd89e99db5120bcb6691b83a4de124814173e"},"downloads":-1,"filename":"logging_error_custom-0.7-py3-none-any.whl","has_sig":false,"md5_digest":"b72f06c83224704e2c8bb667bb2de721","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":2987,"upload_time":"2024-08-14T06:24:14","upload_time_iso_8601":"2024-08-14T06:24:14.023556Z","url":"https://files.pythonhosted.org/packages/ee/68/07fba897b22a6ab342563ac117787a8e257487f22f86f656fda212b01921/logging_error_custom-0.7-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"49c65265262dd1dc6b9885c07d61748e8cdfe795070dd8a2443360c889258a5f","md5":"f98f2550a310da61ec0e0443fc9bc55a","sha256":"a1bc978b7181717799e47c1d73d93f8a04341f6cef55de905273c10d42517519"},"downloads":-1,"filename":"logging_error_custom-0.7.tar.gz","has_sig":false,"md5_digest":"f98f2550a310da61ec0e0443fc9bc55a","packagetype":"sdist","python_version":"source","requires_python":null,"size":2520,"upload_time":"2024-08-14T06:24:15","upload_time_iso_8601":"2024-08-14T06:24:15.554607Z","url":"https://files.pythonhosted.org/packages/49/c6/5265262dd1dc6b9885c07d61748e8cdfe795070dd8a2443360c889258a5f/logging_error_custom-0.7.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.8":{"info":{"author":"Aayush Chaudhary","author_email":"aayush18702@example.com","bugtrack_url":null,"classifiers":[],"description_content_type":null,"docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":null,"license":null,"maintainer":null,"maintainer_email":null,"name":"logging-error-custom","package_url":"https://pypi.org/project/logging-error-custom/","platform":null,"project_url":"https://pypi.org/project/logging-error-custom/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/logging-error-custom/0.8/","requires_dist":["mysql-connector-python","python-dotenv"],"requires_python":null,"summary":"A library for logging exceptions to a MySQL database.","version":"0.8","yanked":false,"yanked_reason":null},"last_serial":24645707,"urls":[{"comment_text":"","digests":{"blake2b_256":"e9bafb2a6a02227f5c856f684d09cb534312e94879217328dd4d35a95515926c","md5":"4e970fb839023d04657c5828286a200d","sha256":"a034985ebe2bcd4bca9a0e45cc200a6f7cb191609e1092c475558626880dd568"},"downloads":-1,"filename":"logging_error_custom-0.8-py3-none-any.whl","has_sig":false,"md5_digest":"4e970fb839023d04657c5828286a200d","packagetype":"bdist_wheel","python_version":"py3","requires_python":null,"size":3120,"upload_time":"2024-08-14T06:30:30","upload_time_iso_8601":"2024-08-14T06:30:30.791458Z","url":"https://files.pythonhosted.org/packages/e9/ba/fb2a6a02227f5c856f684d09cb534312e94879217328dd4d35a95515926c/logging_error_custom-0.8-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"f58a33efd12bb65e1455189a6f9b2ca92c0297d3d0f7040dd4f2c2085d58a57b","md5":"8c65b03bacc84fbc21d105bd8591e539","sha256":"723e6394762f3f2f505eba97f360ec93a0a75bedfbcfd95becd671cd79be14ab"},"downloads":-1,"filename":"logging_error_custom-0.8.tar.gz","has_sig":false,"md5_digest":"8c65b03bacc84fbc21d105bd8591e539","packagetype":"sdist","python_version":"source","requires_python":null,"size":2618,"upload_time":"2024-08-14T06:30:32","upload_time_iso_8601":"2024-08-14T06:30:32.301246Z","url":"https://files.pythonhosted.org/packages/f5/8a/33efd12bb65e1455189a6f9b2ca92c0297d3d0f7040dd4f2c2085d58a57b/logging_error_custom-0.8.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}