{"1.0":{"info":{"author":"Plone Security Team","author_email":"security@plone.org","bugtrack_url":null,"classifiers":["Framework :: Plone","Programming Language :: Python"],"description_content_type":null,"docs_url":null,"download_url":"UNKNOWN","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"http://github.com/plone","keywords":"plone security hotfix patch","license":"GPL","maintainer":"","maintainer_email":"","name":"Products.PloneHotfix20131210","package_url":"https://pypi.org/project/Products.PloneHotfix20131210/","platform":"UNKNOWN","project_url":"https://pypi.org/project/Products.PloneHotfix20131210/","project_urls":{"Download":"UNKNOWN","Homepage":"http://github.com/plone"},"provides_extra":null,"release_url":"https://pypi.org/project/Products.PloneHotfix20131210/1.0/","requires_dist":null,"requires_python":null,"summary":"Various Plone hotfixes, 2013-12-10","version":"1.0","yanked":false,"yanked_reason":null},"last_serial":21064607,"urls":[{"comment_text":"","digests":{"blake2b_256":"1222062684a479a7f6eeb0d2a3da04d5a2c9245ec06ca5f17cb821f7f8179828","md5":"f1febcdf21d0ad84f97407aa9cc2f4e8","sha256":"e161b4f80af85a0808d56a03a8391d787c607f41fe79d34a22e45ecf9e39443e"},"downloads":-1,"filename":"Products.PloneHotfix20131210-1.0.tar.gz","has_sig":false,"md5_digest":"f1febcdf21d0ad84f97407aa9cc2f4e8","packagetype":"sdist","python_version":"source","requires_python":null,"size":11886,"upload_time":"2013-12-10T14:58:11","upload_time_iso_8601":"2013-12-10T14:58:11.582539Z","url":"https://files.pythonhosted.org/packages/12/22/062684a479a7f6eeb0d2a3da04d5a2c9245ec06ca5f17cb821f7f8179828/Products.PloneHotfix20131210-1.0.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}