{"14.0.1.0.1.dev3":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 14.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo14-addon-account-move-exception","package_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","platform":"","project_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo14-addon-account-move-exception/14.0.1.0.1.dev3/","requires_dist":["odoo14-addon-base-exception","odoo (<14.1dev,>=14.0a)"],"requires_python":">=3.6","summary":"Custom exceptions on account move","version":"14.0.1.0.1.dev3","yanked":false,"yanked_reason":null},"last_serial":21507368,"urls":[{"comment_text":"","digests":{"blake2b_256":"308494f5138a1cbefa80b6fa1ab61dc97f8a4868eb0e7e974ece385025057420","md5":"6ad216f417cd8faf1f729d1de4e20089","sha256":"02baa77c4c81ccd0e430ecac03300abd267a7d60a54cc3d071860eda4b491d2c"},"downloads":-1,"filename":"odoo14_addon_account_move_exception-14.0.1.0.1.dev3-py3-none-any.whl","has_sig":false,"md5_digest":"6ad216f417cd8faf1f729d1de4e20089","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":29938,"upload_time":"2021-11-23T10:25:49","upload_time_iso_8601":"2021-11-23T10:25:49.699974Z","url":"https://files.pythonhosted.org/packages/30/84/94f5138a1cbefa80b6fa1ab61dc97f8a4868eb0e7e974ece385025057420/odoo14_addon_account_move_exception-14.0.1.0.1.dev3-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"14.0.1.0.1.dev5":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 14.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo14-addon-account-move-exception","package_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","platform":"","project_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo14-addon-account-move-exception/14.0.1.0.1.dev5/","requires_dist":["odoo14-addon-base-exception","odoo (<14.1dev,>=14.0a)"],"requires_python":">=3.6","summary":"Custom exceptions on account move","version":"14.0.1.0.1.dev5","yanked":false,"yanked_reason":null},"last_serial":21507368,"urls":[{"comment_text":"","digests":{"blake2b_256":"5b7ad8b5ce230ba1d1637d0d4a2f18951d4d3c3429abae804b72da32a0390abb","md5":"d3ad5566d8f4e424c1b11ad9ec88f3b1","sha256":"e9f596247d55f954381096bb3931f3b2c91474b1a98a64c73068d4373a512661"},"downloads":-1,"filename":"odoo14_addon_account_move_exception-14.0.1.0.1.dev5-py3-none-any.whl","has_sig":false,"md5_digest":"d3ad5566d8f4e424c1b11ad9ec88f3b1","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":31310,"upload_time":"2022-02-05T02:42:49","upload_time_iso_8601":"2022-02-05T02:42:49.916488Z","url":"https://files.pythonhosted.org/packages/5b/7a/d8b5ce230ba1d1637d0d4a2f18951d4d3c3429abae804b72da32a0390abb/odoo14_addon_account_move_exception-14.0.1.0.1.dev5-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"14.0.1.0.1.dev6":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 14.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo14-addon-account-move-exception","package_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","platform":null,"project_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo14-addon-account-move-exception/14.0.1.0.1.dev6/","requires_dist":["odoo14-addon-base-exception","odoo <14.1dev,>=14.0a"],"requires_python":">=3.6","summary":"Custom exceptions on account move","version":"14.0.1.0.1.dev6","yanked":false,"yanked_reason":null},"last_serial":21507368,"urls":[{"comment_text":"","digests":{"blake2b_256":"514592527bbd1e361a0193ffdc61f810b2a59968f9d2784fe168c02658342e72","md5":"d6bfaf77ab3c1ec5439a5c5182668ed9","sha256":"6a21ab864bb514ef6194dba01d9a9f1a60164fa8548be1f688654c871738aab6"},"downloads":-1,"filename":"odoo14_addon_account_move_exception-14.0.1.0.1.dev6-py3-none-any.whl","has_sig":false,"md5_digest":"d6bfaf77ab3c1ec5439a5c5182668ed9","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":31618,"upload_time":"2023-09-03T11:35:03","upload_time_iso_8601":"2023-09-03T11:35:03.132720Z","url":"https://files.pythonhosted.org/packages/51/45/92527bbd1e361a0193ffdc61f810b2a59968f9d2784fe168c02658342e72/odoo14_addon_account_move_exception-14.0.1.0.1.dev6-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"14.0.1.0.1.dev9":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 14.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo14-addon-account-move-exception","package_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","platform":null,"project_url":"https://pypi.org/project/odoo14-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo14-addon-account-move-exception/14.0.1.0.1.dev9/","requires_dist":["odoo14-addon-base-exception","odoo <14.1dev,>=14.0a"],"requires_python":">=3.6","summary":"Custom exceptions on account move","version":"14.0.1.0.1.dev9","yanked":false,"yanked_reason":null},"last_serial":21507368,"urls":[{"comment_text":"","digests":{"blake2b_256":"1176cc3fc3588d5da4e341c76febe9891c73996011e9c33ff95796017bfdcbec","md5":"ab218513d003f6dcfcc71fc09d9ab23b","sha256":"e0d760a097528c36f2b3e60b7f4eb50a97741def2e7b3bd2c8b934f87c124c1b"},"downloads":-1,"filename":"odoo14_addon_account_move_exception-14.0.1.0.1.dev9-py3-none-any.whl","has_sig":false,"md5_digest":"ab218513d003f6dcfcc71fc09d9ab23b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":33360,"upload_time":"2024-01-20T02:53:35","upload_time_iso_8601":"2024-01-20T02:53:35.515960Z","url":"https://files.pythonhosted.org/packages/11/76/cc3fc3588d5da4e341c76febe9891c73996011e9c33ff95796017bfdcbec/odoo14_addon_account_move_exception-14.0.1.0.1.dev9-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}