{"15.0.1.0.0.2":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 15.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo-addon-account-move-exception","package_url":"https://pypi.org/project/odoo-addon-account-move-exception/","platform":null,"project_url":"https://pypi.org/project/odoo-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo-addon-account-move-exception/15.0.1.0.0.2/","requires_dist":["odoo-addon-base-exception (<15.1dev,>=15.0dev)","odoo (<15.1dev,>=15.0a)"],"requires_python":">=3.8","summary":"Custom exceptions on account move","version":"15.0.1.0.0.2","yanked":false,"yanked_reason":null},"last_serial":20112330,"urls":[{"comment_text":"","digests":{"blake2b_256":"12d3e41c54fc2dbd892ddd3dd670e11b42033a16d29948084f03c56917d460f9","md5":"e9bda7ed5aa7a2db028359d4f4618a41","sha256":"48132d35ccff4d8cb48af8a59a95641c28a052c0a28ca1807b66365ee98d2b92"},"downloads":-1,"filename":"odoo_addon_account_move_exception-15.0.1.0.0.2-py3-none-any.whl","has_sig":false,"md5_digest":"e9bda7ed5aa7a2db028359d4f4618a41","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":31227,"upload_time":"2022-08-05T09:59:57","upload_time_iso_8601":"2022-08-05T09:59:57.966799Z","url":"https://files.pythonhosted.org/packages/12/d3/e41c54fc2dbd892ddd3dd670e11b42033a16d29948084f03c56917d460f9/odoo_addon_account_move_exception-15.0.1.0.0.2-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"15.0.1.0.0.4":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 15.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo-addon-account-move-exception","package_url":"https://pypi.org/project/odoo-addon-account-move-exception/","platform":null,"project_url":"https://pypi.org/project/odoo-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo-addon-account-move-exception/15.0.1.0.0.4/","requires_dist":["odoo-addon-base-exception (<15.1dev,>=15.0dev)","odoo (<15.1dev,>=15.0a)"],"requires_python":">=3.8","summary":"Custom exceptions on account move","version":"15.0.1.0.0.4","yanked":false,"yanked_reason":null},"last_serial":20112330,"urls":[{"comment_text":"","digests":{"blake2b_256":"99062f34c489f0b0b3db4e7157a333a2c3800169a55fa4946f0d9e7d7fbc5d97","md5":"6e05b6cf595b97400fa839a2c16ee659","sha256":"d9c4835c65402f21e2d176d52d3856e7975a4796bc89f3b7bf4fe7e8af94d248"},"downloads":-1,"filename":"odoo_addon_account_move_exception-15.0.1.0.0.4-py3-none-any.whl","has_sig":false,"md5_digest":"6e05b6cf595b97400fa839a2c16ee659","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":32764,"upload_time":"2022-09-22T02:42:41","upload_time_iso_8601":"2022-09-22T02:42:41.404182Z","url":"https://files.pythonhosted.org/packages/99/06/2f34c489f0b0b3db4e7157a333a2c3800169a55fa4946f0d9e7d7fbc5d97/odoo_addon_account_move_exception-15.0.1.0.0.4-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"15.0.1.0.0.5":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 15.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo-addon-account-move-exception","package_url":"https://pypi.org/project/odoo-addon-account-move-exception/","platform":null,"project_url":"https://pypi.org/project/odoo-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo-addon-account-move-exception/15.0.1.0.0.5/","requires_dist":["odoo-addon-base-exception <15.1dev,>=15.0dev","odoo <15.1dev,>=15.0a"],"requires_python":">=3.8","summary":"Custom exceptions on account move","version":"15.0.1.0.0.5","yanked":false,"yanked_reason":null},"last_serial":20112330,"urls":[{"comment_text":"","digests":{"blake2b_256":"333ecb4b2fdfd6c217a1949a55f1db8bcd8a5a57293cec045ff5fb35fe60bdc8","md5":"540bab6d993f6100e59a98b2eb2d04e4","sha256":"8e749db518f844fdabc15eef400e0db944ae6709bfb56ea0b2d279237169e640"},"downloads":-1,"filename":"odoo_addon_account_move_exception-15.0.1.0.0.5-py3-none-any.whl","has_sig":false,"md5_digest":"540bab6d993f6100e59a98b2eb2d04e4","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":33077,"upload_time":"2023-09-03T11:35:36","upload_time_iso_8601":"2023-09-03T11:35:36.758801Z","url":"https://files.pythonhosted.org/packages/33/3e/cb4b2fdfd6c217a1949a55f1db8bcd8a5a57293cec045ff5fb35fe60bdc8/odoo_addon_account_move_exception-15.0.1.0.0.5-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"15.0.1.0.0.7":{"info":{"author":"ForgeFlow, Odoo Community Association (OCA)","author_email":"support@odoo-community.org","bugtrack_url":null,"classifiers":["Framework :: Odoo","Framework :: Odoo :: 15.0","License :: OSI Approved :: GNU Affero General Public License v3","Programming Language :: Python"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/OCA/account-invoicing","keywords":"","license":"AGPL-3","maintainer":"","maintainer_email":"","name":"odoo-addon-account-move-exception","package_url":"https://pypi.org/project/odoo-addon-account-move-exception/","platform":null,"project_url":"https://pypi.org/project/odoo-addon-account-move-exception/","project_urls":{"Homepage":"https://github.com/OCA/account-invoicing"},"provides_extra":null,"release_url":"https://pypi.org/project/odoo-addon-account-move-exception/15.0.1.0.0.7/","requires_dist":["odoo-addon-base-exception <15.1dev,>=15.0dev","odoo <15.1dev,>=15.0a"],"requires_python":">=3.8","summary":"Custom exceptions on account move","version":"15.0.1.0.0.7","yanked":false,"yanked_reason":null},"last_serial":20112330,"urls":[{"comment_text":"","digests":{"blake2b_256":"f3a02919260957da31e42c3f47a4c5fd0a62d0c857cae7062f6448330ba7977b","md5":"530fba6b8e90eac6ffe16c8da12a35d1","sha256":"fa4e58f432f1209bcc803a99593b591085f02aadc2a61c25a4e281601d298e0b"},"downloads":-1,"filename":"odoo_addon_account_move_exception-15.0.1.0.0.7-py3-none-any.whl","has_sig":false,"md5_digest":"530fba6b8e90eac6ffe16c8da12a35d1","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.8","size":33171,"upload_time":"2023-10-11T02:54:38","upload_time_iso_8601":"2023-10-11T02:54:38.949135Z","url":"https://files.pythonhosted.org/packages/f3/a0/2919260957da31e42c3f47a4c5fd0a62d0c857cae7062f6448330ba7977b/odoo_addon_account_move_exception-15.0.1.0.0.7-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}