{"0.1.6":{"info":{"author":"Jonas Maurus (@jdelic)","author_email":"jonas-dbconn-retry@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"GoPythonGo.com","maintainer_email":"info@gopythongo.com","name":"django-dbconn-retry-coreteam","package_url":"https://pypi.org/project/django-dbconn-retry-coreteam/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry-coreteam/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry-coreteam/0.1.6/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.6","yanked":false,"yanked_reason":null},"last_serial":7164531,"urls":[{"comment_text":"","digests":{"blake2b_256":"b8ab0bc3e0f64fae91b7884d1fd8352d07fc396bc72b1b2644a61812d8196b17","md5":"90fdc860a99ae98e5e5d39641295cf47","sha256":"d7f35dddc3e486c1c2fec07066384905aaa71bebcaec371bb8285815776ebde4"},"downloads":-1,"filename":"django-dbconn-retry-coreteam-0.1.6.tar.gz","has_sig":false,"md5_digest":"90fdc860a99ae98e5e5d39641295cf47","packagetype":"sdist","python_version":"source","requires_python":null,"size":7852,"upload_time":"2020-05-04T13:32:54","upload_time_iso_8601":"2020-05-04T13:32:54.550195Z","url":"https://files.pythonhosted.org/packages/b8/ab/0bc3e0f64fae91b7884d1fd8352d07fc396bc72b1b2644a61812d8196b17/django-dbconn-retry-coreteam-0.1.6.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.7":{"info":{"author":"Jonas Maurus (@jdelic)","author_email":"jonas-dbconn-retry@gopythongo.com","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","Intended Audience :: System Administrators","License :: OSI Approved :: BSD License","Operating System :: POSIX","Programming Language :: Python :: 3 :: Only"],"description_content_type":"","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/jdelic/django-dbconn-retry/","keywords":"","license":"","maintainer":"GoPythonGo.com","maintainer_email":"info@gopythongo.com","name":"django-dbconn-retry-coreteam","package_url":"https://pypi.org/project/django-dbconn-retry-coreteam/","platform":"","project_url":"https://pypi.org/project/django-dbconn-retry-coreteam/","project_urls":{"Homepage":"https://github.com/jdelic/django-dbconn-retry/"},"provides_extra":null,"release_url":"https://pypi.org/project/django-dbconn-retry-coreteam/0.1.7/","requires_dist":null,"requires_python":"","summary":"Patch Django to retry a database connection first before failing.","version":"0.1.7","yanked":false,"yanked_reason":null},"last_serial":7164531,"urls":[{"comment_text":"","digests":{"blake2b_256":"e940cccc02d64c453783bdcd7eb3712283fa078e58db3924970b6ffc5fd21250","md5":"8250aab523c16014ebfd7bc90eacf9de","sha256":"05bd78401e8a97b567c4ce80d1996e9ed258d8ef0f300e20555d0e13500083e9"},"downloads":-1,"filename":"django-dbconn-retry-coreteam-0.1.7.tar.gz","has_sig":false,"md5_digest":"8250aab523c16014ebfd7bc90eacf9de","packagetype":"sdist","python_version":"source","requires_python":null,"size":7852,"upload_time":"2020-05-04T13:40:57","upload_time_iso_8601":"2020-05-04T13:40:57.075878Z","url":"https://files.pythonhosted.org/packages/e9/40/cccc02d64c453783bdcd7eb3712283fa078e58db3924970b6ffc5fd21250/django-dbconn-retry-coreteam-0.1.7.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}