{"0.1.1":{"info":{"author":"Jay Young(yjmade)","author_email":"dev@yjmade.net","bugtrack_url":null,"classifiers":["Development Status :: 4 - Beta","Intended Audience :: Developers","License :: OSI Approved :: ISC License (ISCL)","Programming Language :: Python :: 3","Programming Language :: Python :: 3.4","Programming Language :: Python :: 3.5"],"description_content_type":null,"docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"https://github.com/yjmade/django-celery-errorlog","keywords":"django celery error log report","license":"MIT","maintainer":"","maintainer_email":"","name":"django-celery-errorlog","package_url":"https://pypi.org/project/django-celery-errorlog/","platform":"","project_url":"https://pypi.org/project/django-celery-errorlog/","project_urls":{"Homepage":"https://github.com/yjmade/django-celery-errorlog"},"provides_extra":null,"release_url":"https://pypi.org/project/django-celery-errorlog/0.1.1/","requires_dist":null,"requires_python":"","summary":"Reuseable app for django to collect the unexpted exception and generate comprehansive report just like what you get in debug mode and store in database from celery task","version":"0.1.1","yanked":false,"yanked_reason":null},"last_serial":2500513,"urls":[{"comment_text":"","digests":{"blake2b_256":"0ee794d7c5f8dea4d0621ad16ff700a4a0e1363c9b78abd9a9b49fdb6cb9623b","md5":"3a2b657ef92770a83b6f1a7968261625","sha256":"28ebbca85089e31b802305207d2a5feb810d7af34cae4dfce02588dce5430ab8"},"downloads":-1,"filename":"django-celery-errorlog-0.1.1.tar.gz","has_sig":false,"md5_digest":"3a2b657ef92770a83b6f1a7968261625","packagetype":"sdist","python_version":"source","requires_python":null,"size":4864,"upload_time":"2016-12-05T14:57:35","upload_time_iso_8601":"2016-12-05T14:57:35.686906Z","url":"https://files.pythonhosted.org/packages/0e/e7/94d7c5f8dea4d0621ad16ff700a4a0e1363c9b78abd9a9b49fdb6cb9623b/django-celery-errorlog-0.1.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}