{"0.1.0":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.0/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.0","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"db1e617fc4742e2166f78ad37937c19add79103f33a017ce131621b0a9385fab","md5":"729cea806e402fc7d40f2b57a9055504","sha256":"39d1d131913ca39385c09de98f116d967d300384afbcb845f915bc04b7f5c105"},"downloads":-1,"filename":"teleexception-0.1.0-py3-none-any.whl","has_sig":false,"md5_digest":"729cea806e402fc7d40f2b57a9055504","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":4918,"upload_time":"2022-05-20T08:07:53","upload_time_iso_8601":"2022-05-20T08:07:53.089991Z","url":"https://files.pythonhosted.org/packages/db/1e/617fc4742e2166f78ad37937c19add79103f33a017ce131621b0a9385fab/teleexception-0.1.0-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.1":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.1/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.1","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"c72d81344b51bb947620c812b84a5383098d9ea92f67c6b0c3cc89a2ccb01c7f","md5":"40fd35f83d5322d54b3452191992f342","sha256":"d2e8563434315aefa1f8890696e52c59e6d7048cf90eb020ca23c6b57a3ed189"},"downloads":-1,"filename":"teleexception-0.1.1-py3-none-any.whl","has_sig":false,"md5_digest":"40fd35f83d5322d54b3452191992f342","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5858,"upload_time":"2022-06-13T10:19:46","upload_time_iso_8601":"2022-06-13T10:19:46.012739Z","url":"https://files.pythonhosted.org/packages/c7/2d/81344b51bb947620c812b84a5383098d9ea92f67c6b0c3cc89a2ccb01c7f/teleexception-0.1.1-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.10":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.10/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.10","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"823bfd8372b6148c9000ec186ae2ebd9ca911cdafa691f75cca4ae172c82901b","md5":"8eb01630f74f11c64d4d607091cf0b5f","sha256":"d31c7bd2b7fd450ff17f3bc7d3a893b0957fdd61554d6998bb4d61cfb6dfaca7"},"downloads":-1,"filename":"teleexception-0.1.10-py3-none-any.whl","has_sig":false,"md5_digest":"8eb01630f74f11c64d4d607091cf0b5f","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5796,"upload_time":"2022-08-16T03:04:07","upload_time_iso_8601":"2022-08-16T03:04:07.359318Z","url":"https://files.pythonhosted.org/packages/82/3b/fd8372b6148c9000ec186ae2ebd9ca911cdafa691f75cca4ae172c82901b/teleexception-0.1.10-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.11":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.11/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.11","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"689c9716d8dfbdfe76c4955e14a672012100f32beb227176d7a5a1d22c19e9ba","md5":"20ca691eaf1381e49b83a161f9840d6b","sha256":"30ea064789712828f9267a98541cd7a09a7bafcf5d2ac600a6f4e601de493cff"},"downloads":-1,"filename":"teleexception-0.1.11-py3-none-any.whl","has_sig":false,"md5_digest":"20ca691eaf1381e49b83a161f9840d6b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5912,"upload_time":"2022-08-25T00:57:57","upload_time_iso_8601":"2022-08-25T00:57:57.345113Z","url":"https://files.pythonhosted.org/packages/68/9c/9716d8dfbdfe76c4955e14a672012100f32beb227176d7a5a1d22c19e9ba/teleexception-0.1.11-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.12":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.12/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.12","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"1e20409816d7d3a39995974708b3564fd27e315a210e73bc99bc2facb2ee50c3","md5":"53d35b1665226f77b031aaa05a13ffad","sha256":"9c40b571f46f6aea79ae2cb3bcc3b23366187327411e17f24f19853a09eba629"},"downloads":-1,"filename":"teleexception-0.1.12-py3-none-any.whl","has_sig":false,"md5_digest":"53d35b1665226f77b031aaa05a13ffad","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5975,"upload_time":"2022-08-31T01:03:10","upload_time_iso_8601":"2022-08-31T01:03:10.660044Z","url":"https://files.pythonhosted.org/packages/1e/20/409816d7d3a39995974708b3564fd27e315a210e73bc99bc2facb2ee50c3/teleexception-0.1.12-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.13":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.13/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.13","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"5480e9b66372a5edc545ef9a345fde0d5e9e12fe70234c1eeb6a5810e2a4efad","md5":"4394797e35dbace07ec1c563cbc99b0d","sha256":"14c1ab4be791aa5b99377dbdd4dca5d3b910d77b0400137ec17fb407f4732381"},"downloads":-1,"filename":"teleexception-0.1.13-py3-none-any.whl","has_sig":false,"md5_digest":"4394797e35dbace07ec1c563cbc99b0d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6039,"upload_time":"2022-09-02T08:28:16","upload_time_iso_8601":"2022-09-02T08:28:16.106340Z","url":"https://files.pythonhosted.org/packages/54/80/e9b66372a5edc545ef9a345fde0d5e9e12fe70234c1eeb6a5810e2a4efad/teleexception-0.1.13-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.14":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.14/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.14","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"2fca8f709c1050b7da32c4c5584e6a1425d7bf834e2859480a33ecd52bc9d854","md5":"ef4261365825850413200bcf9338cb4d","sha256":"3d7554f9e7c81fe360268333e72127711a1c8c018a29b4083bcd280241e070f6"},"downloads":-1,"filename":"teleexception-0.1.14-py3-none-any.whl","has_sig":false,"md5_digest":"ef4261365825850413200bcf9338cb4d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6183,"upload_time":"2022-09-07T06:28:18","upload_time_iso_8601":"2022-09-07T06:28:18.337034Z","url":"https://files.pythonhosted.org/packages/2f/ca/8f709c1050b7da32c4c5584e6a1425d7bf834e2859480a33ecd52bc9d854/teleexception-0.1.14-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.15":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.15/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.15","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"d1b6478abd1db887aab9faa37fc0c233040dc921d3fc4b992ac02121ab657c32","md5":"2d31af5a7484ae662fffeadab938362f","sha256":"cc9766dfcdc09e3da53b23c11852ce4b37b59196f544484e0801224f5675920f"},"downloads":-1,"filename":"teleexception-0.1.15-py3-none-any.whl","has_sig":false,"md5_digest":"2d31af5a7484ae662fffeadab938362f","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6231,"upload_time":"2022-09-09T02:24:29","upload_time_iso_8601":"2022-09-09T02:24:29.626480Z","url":"https://files.pythonhosted.org/packages/d1/b6/478abd1db887aab9faa37fc0c233040dc921d3fc4b992ac02121ab657c32/teleexception-0.1.15-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.16":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.16/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.16","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"bf127d29d458b2793478614a750a492341d7f6a1d535866d8938b7464b56899d","md5":"48f3907ff90a34ca38f25b66f39f5af1","sha256":"9d0ea6174746846971ab6f8fa16463324e78eec4838b97c189a89e035a16d433"},"downloads":-1,"filename":"teleexception-0.1.16-py3-none-any.whl","has_sig":false,"md5_digest":"48f3907ff90a34ca38f25b66f39f5af1","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6324,"upload_time":"2022-09-13T01:40:26","upload_time_iso_8601":"2022-09-13T01:40:26.172641Z","url":"https://files.pythonhosted.org/packages/bf/12/7d29d458b2793478614a750a492341d7f6a1d535866d8938b7464b56899d/teleexception-0.1.16-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.17":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.17/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.17","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"1904a874c3bae0cb074db7460ad8660bc19c105a7c7e19887b1d06bc50a52d11","md5":"af8ee52b3c84161d0422eef32bef855e","sha256":"c8496cf304ae9f42e2683fe356ef0261a393c41f49912039f1549ce8f70b96c9"},"downloads":-1,"filename":"teleexception-0.1.17-py3-none-any.whl","has_sig":false,"md5_digest":"af8ee52b3c84161d0422eef32bef855e","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6922,"upload_time":"2022-10-08T03:17:25","upload_time_iso_8601":"2022-10-08T03:17:25.096894Z","url":"https://files.pythonhosted.org/packages/19/04/a874c3bae0cb074db7460ad8660bc19c105a7c7e19887b1d06bc50a52d11/teleexception-0.1.17-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.18":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.18/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.18","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"acf936e942427339ef02148292b0f25f8d4d6e70a1efd41f425b461b2dd453e8","md5":"6be2c58ed19c645662b2da55476d136b","sha256":"bd571397b2e5e906ec4ff180a0f114cb91d859f37aaea2665ac8d9bea08393d7"},"downloads":-1,"filename":"teleexception-0.1.18-py3-none-any.whl","has_sig":false,"md5_digest":"6be2c58ed19c645662b2da55476d136b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":7439,"upload_time":"2022-10-11T01:26:16","upload_time_iso_8601":"2022-10-11T01:26:16.519327Z","url":"https://files.pythonhosted.org/packages/ac/f9/36e942427339ef02148292b0f25f8d4d6e70a1efd41f425b461b2dd453e8/teleexception-0.1.18-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.19":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.19/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.19","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"e930c6e90db22ab7df3968dfc28eb512973085147ea8023230e2525999cbd236","md5":"0c88cac8f8140e8b35930f465300d034","sha256":"0cb6a7368936a34598b96987219de9f97556ee28ef28f842f1e10a09faa19f13"},"downloads":-1,"filename":"teleexception-0.1.19-py3-none-any.whl","has_sig":false,"md5_digest":"0c88cac8f8140e8b35930f465300d034","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":7486,"upload_time":"2022-10-14T07:28:31","upload_time_iso_8601":"2022-10-14T07:28:31.153079Z","url":"https://files.pythonhosted.org/packages/e9/30/c6e90db22ab7df3968dfc28eb512973085147ea8023230e2525999cbd236/teleexception-0.1.19-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.2":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.2/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.2","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"9cacd73f6ab222cd59400bc4b3f8b8080d3909428080e9fc08bbede29971eaef","md5":"5f0598a72c9fa10ba7592bdcc41e6e94","sha256":"af3c29423b95d8c43a96a5f011e0e0eb3dea9faa6f6bb1a2e02d8853ed6607d7"},"downloads":-1,"filename":"teleexception-0.1.2-py3-none-any.whl","has_sig":false,"md5_digest":"5f0598a72c9fa10ba7592bdcc41e6e94","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5858,"upload_time":"2022-06-14T03:42:12","upload_time_iso_8601":"2022-06-14T03:42:12.262571Z","url":"https://files.pythonhosted.org/packages/9c/ac/d73f6ab222cd59400bc4b3f8b8080d3909428080e9fc08bbede29971eaef/teleexception-0.1.2-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.20":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.20/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.20","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"64a8b884e68170633496a8578d9363f9debbd8a8d5f6f69b8d7297ce61023f0b","md5":"4321730516a680a2167dea43b3bd55b4","sha256":"1e8e38d7c619a2a657572b61e16790fec00385bca0b3f4e83c1ec08f304dbf0d"},"downloads":-1,"filename":"teleexception-0.1.20-py3-none-any.whl","has_sig":false,"md5_digest":"4321730516a680a2167dea43b3bd55b4","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":7499,"upload_time":"2022-10-17T02:11:31","upload_time_iso_8601":"2022-10-17T02:11:31.420869Z","url":"https://files.pythonhosted.org/packages/64/a8/b884e68170633496a8578d9363f9debbd8a8d5f6f69b8d7297ce61023f0b/teleexception-0.1.20-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.21":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.21/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.21","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"414a2b95f01662df66ec8c22dff117d8c9d4a01ad128639c39fc428e5ec9391e","md5":"db65af01d1a807db9f06091134056435","sha256":"c99d2d68f97267fc946ae35c8fc26ccdcd80d9ecccf2fe80bbe11842c398c54e"},"downloads":-1,"filename":"teleexception-0.1.21-py3-none-any.whl","has_sig":false,"md5_digest":"db65af01d1a807db9f06091134056435","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":7502,"upload_time":"2022-10-17T06:44:04","upload_time_iso_8601":"2022-10-17T06:44:04.381902Z","url":"https://files.pythonhosted.org/packages/41/4a/2b95f01662df66ec8c22dff117d8c9d4a01ad128639c39fc428e5ec9391e/teleexception-0.1.21-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.3":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.3/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.3","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"3d1a7c763c63c9695395dfeadb5d9a0c2ae6d9c9540a3ab350bc1c58f117dd05","md5":"c2569042b60708ab10322165c6d7b066","sha256":"4d90ba3dc276253e2051880e4b6691412ef064c53f13bd47ddb6ef170801ebcd"},"downloads":-1,"filename":"teleexception-0.1.3-py3-none-any.whl","has_sig":false,"md5_digest":"c2569042b60708ab10322165c6d7b066","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5801,"upload_time":"2022-06-15T02:46:12","upload_time_iso_8601":"2022-06-15T02:46:12.189509Z","url":"https://files.pythonhosted.org/packages/3d/1a/7c763c63c9695395dfeadb5d9a0c2ae6d9c9540a3ab350bc1c58f117dd05/teleexception-0.1.3-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.4":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.4/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.4","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"2b2f69f2804873ed414c9c03821bdb973e0107c9324fa04f91955986138bd2ee","md5":"c618e2c241f498cf91864ec37c53db85","sha256":"51684cf1550861ed7e72c3a8436eb08c253626f0f9d21fe6c9935b103ac51618"},"downloads":-1,"filename":"teleexception-0.1.4-py3-none-any.whl","has_sig":false,"md5_digest":"c618e2c241f498cf91864ec37c53db85","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6198,"upload_time":"2022-07-19T11:16:18","upload_time_iso_8601":"2022-07-19T11:16:18.061146Z","url":"https://files.pythonhosted.org/packages/2b/2f/69f2804873ed414c9c03821bdb973e0107c9324fa04f91955986138bd2ee/teleexception-0.1.4-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.5":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.5/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.5","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"e95a5574c0fc321ac99056bef6410820835d19b61305016907c7161ead0857cf","md5":"7b6451ed158c6f320d5ceedbc4060427","sha256":"ddeb601b38f2d4cd7c5638845dc5664fe6ca14b28c268fbcd6415d16ae06301f"},"downloads":-1,"filename":"teleexception-0.1.5-py3-none-any.whl","has_sig":false,"md5_digest":"7b6451ed158c6f320d5ceedbc4060427","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":6605,"upload_time":"2022-07-20T07:44:26","upload_time_iso_8601":"2022-07-20T07:44:26.739112Z","url":"https://files.pythonhosted.org/packages/e9/5a/5574c0fc321ac99056bef6410820835d19b61305016907c7161ead0857cf/teleexception-0.1.5-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.6":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.6/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.6","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"5cd014c08fdcebbe655e5a95516cff3093cead84b59a4066d3391994218eda39","md5":"1af0a69d0d656ea51ff09fb8a6c6e516","sha256":"1c27b0a9d3e7fc95987367fdecf1c67bf0c4a54d338eecd292de5fdace87b155"},"downloads":-1,"filename":"teleexception-0.1.6-py3-none-any.whl","has_sig":false,"md5_digest":"1af0a69d0d656ea51ff09fb8a6c6e516","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":7116,"upload_time":"2022-07-27T07:45:01","upload_time_iso_8601":"2022-07-27T07:45:01.944880Z","url":"https://files.pythonhosted.org/packages/5c/d0/14c08fdcebbe655e5a95516cff3093cead84b59a4066d3391994218eda39/teleexception-0.1.6-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.7":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.7/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.7","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"291229851c31a19bf9ee53ddb7da05b1eab791794f6580a33fa9dbe6fe54d063","md5":"06e66ace251a2096955d7d518e4ae680","sha256":"ba2d4aff711088e7de5464a1b7aa28f7a91bb4c600b3a112ba5402057418c264"},"downloads":-1,"filename":"teleexception-0.1.7-py3-none-any.whl","has_sig":false,"md5_digest":"06e66ace251a2096955d7d518e4ae680","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":7107,"upload_time":"2022-07-27T09:14:09","upload_time_iso_8601":"2022-07-27T09:14:09.064193Z","url":"https://files.pythonhosted.org/packages/29/12/29851c31a19bf9ee53ddb7da05b1eab791794f6580a33fa9dbe6fe54d063/teleexception-0.1.7-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.8":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.8/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.8","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"5280d37002e21bdf156dac50aa61d3b86ad8c528a6dc19ac18863a9b0e486040","md5":"d94d36ae5af1f5b636908818f84572c8","sha256":"ed75071ea01029febd7e2b36ad697224e25ee72a9c970e27ccecdd60a687647b"},"downloads":-1,"filename":"teleexception-0.1.8-py3-none-any.whl","has_sig":false,"md5_digest":"d94d36ae5af1f5b636908818f84572c8","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5531,"upload_time":"2022-08-05T03:37:26","upload_time_iso_8601":"2022-08-05T03:37:26.217049Z","url":"https://files.pythonhosted.org/packages/52/80/d37002e21bdf156dac50aa61d3b86ad8c528a6dc19ac18863a9b0e486040/teleexception-0.1.8-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.1.9":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.1.9/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.1.9","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"1d205149a81e6ad95567ea42f9a8f118d67e0921ea271fa605021c177449a844","md5":"3647d7112a3f4ea8193c597f5500df25","sha256":"210bfb5f0f9376cbaae5aaffd4116026878db7afc6add5479bbb14fc4d55024b"},"downloads":-1,"filename":"teleexception-0.1.9-py3-none-any.whl","has_sig":false,"md5_digest":"3647d7112a3f4ea8193c597f5500df25","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":5615,"upload_time":"2022-08-08T01:53:54","upload_time_iso_8601":"2022-08-08T01:53:54.874665Z","url":"https://files.pythonhosted.org/packages/1d/20/5149a81e6ad95567ea42f9a8f118d67e0921ea271fa605021c177449a844/teleexception-0.1.9-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.0":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.0/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.0","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"035a3d315b83333aed02f36877bd65a8ad8f6ddae2bec52309da97707ded30e5","md5":"6808c9b48f601d98368c27b984e9eebd","sha256":"8567216b317b2513b391d85d718ce4242ea312e5adb25f1f23ffe2a95db9c900"},"downloads":-1,"filename":"teleexception-0.2.0-py3-none-any.whl","has_sig":false,"md5_digest":"6808c9b48f601d98368c27b984e9eebd","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":8018,"upload_time":"2022-10-19T01:08:07","upload_time_iso_8601":"2022-10-19T01:08:07.654217Z","url":"https://files.pythonhosted.org/packages/03/5a/3d315b83333aed02f36877bd65a8ad8f6ddae2bec52309da97707ded30e5/teleexception-0.2.0-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.1":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.1/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.1","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"544e2bd22c6141420409df4906e0e07e1c176c36e936aa3230bb90bffb9d1807","md5":"141b0332c9cf5a046a27a5b3b8cead2d","sha256":"3df2191796265e7f3ac1a5ac1144157293e0c08036131912489b0aff4ac5d6c3"},"downloads":-1,"filename":"teleexception-0.2.1-py3-none-any.whl","has_sig":false,"md5_digest":"141b0332c9cf5a046a27a5b3b8cead2d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":8078,"upload_time":"2022-10-19T06:20:27","upload_time_iso_8601":"2022-10-19T06:20:27.518224Z","url":"https://files.pythonhosted.org/packages/54/4e/2bd22c6141420409df4906e0e07e1c176c36e936aa3230bb90bffb9d1807/teleexception-0.2.1-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.10":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.10/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.10","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"0e3d5c791f7545588ac0b2068bfa76807e5e7acc4e08e0a310b016174d948e80","md5":"81edc9b4c72eae6d716130801c8a3045","sha256":"a68da3bd66c666dcee44ce47deb55f8544c003a454a42a3bda8e718093494d80"},"downloads":-1,"filename":"teleexception-0.2.10-py3-none-any.whl","has_sig":false,"md5_digest":"81edc9b4c72eae6d716130801c8a3045","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9847,"upload_time":"2022-11-13T11:46:26","upload_time_iso_8601":"2022-11-13T11:46:26.443815Z","url":"https://files.pythonhosted.org/packages/0e/3d/5c791f7545588ac0b2068bfa76807e5e7acc4e08e0a310b016174d948e80/teleexception-0.2.10-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.11":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.11/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.11","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"9347eb3ace61a78df3798edb8de309f1ad4dfd4a99ec53060763674120a6a782","md5":"8fe272df476037557cef14e712927de6","sha256":"ca8eb94197eae9a040ae09f0bb933651b826f3c517f2bc162064f95091fa6be3"},"downloads":-1,"filename":"teleexception-0.2.11-py3-none-any.whl","has_sig":false,"md5_digest":"8fe272df476037557cef14e712927de6","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9876,"upload_time":"2022-11-15T00:40:31","upload_time_iso_8601":"2022-11-15T00:40:31.746262Z","url":"https://files.pythonhosted.org/packages/93/47/eb3ace61a78df3798edb8de309f1ad4dfd4a99ec53060763674120a6a782/teleexception-0.2.11-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.12":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.12/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.12","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"f07c2ab0aa5e97f3c0d1c40dff2d203175871c6741ddc5576b1a3cc7774ba2e9","md5":"a265349222144440d08b7e1361ee786a","sha256":"e9a79615b3d4fa5838c003fcebac408ed29484c9bd7accc1642182ff3ab04346"},"downloads":-1,"filename":"teleexception-0.2.12-py3-none-any.whl","has_sig":false,"md5_digest":"a265349222144440d08b7e1361ee786a","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9927,"upload_time":"2022-11-21T02:38:53","upload_time_iso_8601":"2022-11-21T02:38:53.817794Z","url":"https://files.pythonhosted.org/packages/f0/7c/2ab0aa5e97f3c0d1c40dff2d203175871c6741ddc5576b1a3cc7774ba2e9/teleexception-0.2.12-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.13":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.13/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.13","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"3b2ca7f131e4a626ab45b6e86d8779bc1457a9c97c5cd2c1bb31ab6ee1226f46","md5":"5da0859a57c28cae38ff48cb741aec67","sha256":"df1610c5b1ac7002e35b2a96ddde622e786ec62295653cba44b5ce394781cb81"},"downloads":-1,"filename":"teleexception-0.2.13-py3-none-any.whl","has_sig":false,"md5_digest":"5da0859a57c28cae38ff48cb741aec67","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9943,"upload_time":"2022-11-28T06:17:18","upload_time_iso_8601":"2022-11-28T06:17:18.114288Z","url":"https://files.pythonhosted.org/packages/3b/2c/a7f131e4a626ab45b6e86d8779bc1457a9c97c5cd2c1bb31ab6ee1226f46/teleexception-0.2.13-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.14":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.14/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.14","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"2025ec888b2ef9e092e85c04e069ba8bdfdde7b386be4856a848509496fb87a0","md5":"0b7bb5bd810e558e371b6ce92436db5f","sha256":"468bec8c4eda2034c154e9e627d30ef4ebe676dfca5e5ba0c8ad440c08e7838f"},"downloads":-1,"filename":"teleexception-0.2.14-py3-none-any.whl","has_sig":false,"md5_digest":"0b7bb5bd810e558e371b6ce92436db5f","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9950,"upload_time":"2022-12-06T12:59:09","upload_time_iso_8601":"2022-12-06T12:59:09.431673Z","url":"https://files.pythonhosted.org/packages/20/25/ec888b2ef9e092e85c04e069ba8bdfdde7b386be4856a848509496fb87a0/teleexception-0.2.14-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.16":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.16/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.16","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"643faa83af94014b07150c690965b4b7c350ca1cae46254679f1dd97f57167f3","md5":"84c2df8302a6e166706701f53284255c","sha256":"4270ddeb72a11363d008b682a4a68213f9af1ac6c5c416cad76cb2685b166da8"},"downloads":-1,"filename":"teleexception-0.2.16-py3-none-any.whl","has_sig":false,"md5_digest":"84c2df8302a6e166706701f53284255c","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11781,"upload_time":"2023-01-29T11:06:12","upload_time_iso_8601":"2023-01-29T11:06:12.963292Z","url":"https://files.pythonhosted.org/packages/64/3f/aa83af94014b07150c690965b4b7c350ca1cae46254679f1dd97f57167f3/teleexception-0.2.16-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.2":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.2/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.2","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"5d5c42020b216d55e7d7afbeb488c6ddc710311ca7803f1b7abad54f2eef69fc","md5":"6ab1c2e8d36b99dc7eec1fddd33c16ac","sha256":"cef8cdba000f84c4ef61379df89feae7ccc2c976ddb139b7bb1aa3a8e99c05a1"},"downloads":-1,"filename":"teleexception-0.2.2-py3-none-any.whl","has_sig":false,"md5_digest":"6ab1c2e8d36b99dc7eec1fddd33c16ac","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":8090,"upload_time":"2022-10-19T09:08:14","upload_time_iso_8601":"2022-10-19T09:08:14.930099Z","url":"https://files.pythonhosted.org/packages/5d/5c/42020b216d55e7d7afbeb488c6ddc710311ca7803f1b7abad54f2eef69fc/teleexception-0.2.2-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.3":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.3/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.3","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"f9b51f918bd9791ddb29b95a1560b612b7d585e7ab4f18b1a4833b046732387b","md5":"f126c0f9a787c3ba9f325f5839f0374f","sha256":"53abec861b9fbab23379b2698ce6950780d190e197addd3640d23af182cd11de"},"downloads":-1,"filename":"teleexception-0.2.3-py3-none-any.whl","has_sig":false,"md5_digest":"f126c0f9a787c3ba9f325f5839f0374f","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":8124,"upload_time":"2022-10-20T02:14:12","upload_time_iso_8601":"2022-10-20T02:14:12.382299Z","url":"https://files.pythonhosted.org/packages/f9/b5/1f918bd9791ddb29b95a1560b612b7d585e7ab4f18b1a4833b046732387b/teleexception-0.2.3-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.4":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.4/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.4","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"e81de454452db8335408bea6acd95c7f1e8b71317a8663e4de43ad5e803ea3e1","md5":"d7280617bcc9fcee42a073e0fc1f8247","sha256":"74b1b4ac54563b288c92de5787b57be00795e9e11f7c28c216be6c5392bd456c"},"downloads":-1,"filename":"teleexception-0.2.4-py3-none-any.whl","has_sig":false,"md5_digest":"d7280617bcc9fcee42a073e0fc1f8247","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":8123,"upload_time":"2022-10-21T01:09:15","upload_time_iso_8601":"2022-10-21T01:09:15.851918Z","url":"https://files.pythonhosted.org/packages/e8/1d/e454452db8335408bea6acd95c7f1e8b71317a8663e4de43ad5e803ea3e1/teleexception-0.2.4-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.5":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.5/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.5","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"9ee5249232d2be69641dc6f944adbf41b44152cf569c6607f3bc1111d3797201","md5":"82e8221217c8cf22509c56d7c66472b7","sha256":"0595082020c02e94abb22f9aee97480f931c08e08e3fba13aa6a2f151b908672"},"downloads":-1,"filename":"teleexception-0.2.5-py3-none-any.whl","has_sig":false,"md5_digest":"82e8221217c8cf22509c56d7c66472b7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":8535,"upload_time":"2022-10-28T03:28:30","upload_time_iso_8601":"2022-10-28T03:28:30.623979Z","url":"https://files.pythonhosted.org/packages/9e/e5/249232d2be69641dc6f944adbf41b44152cf569c6607f3bc1111d3797201/teleexception-0.2.5-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.6":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.6/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.6","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"417e7e7404469eb91118652d99e48c4d2f35cd39eb5fca6328f88833c576ba61","md5":"888f68c7cadfc0a121ae4ea9fdd25cf0","sha256":"a3fd32d9d73eec008842d4c65003906fc7f2091f7491d5eba5791c7ef7ff0e41"},"downloads":-1,"filename":"teleexception-0.2.6-py3-none-any.whl","has_sig":false,"md5_digest":"888f68c7cadfc0a121ae4ea9fdd25cf0","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9714,"upload_time":"2022-10-28T08:52:37","upload_time_iso_8601":"2022-10-28T08:52:37.656163Z","url":"https://files.pythonhosted.org/packages/41/7e/7e7404469eb91118652d99e48c4d2f35cd39eb5fca6328f88833c576ba61/teleexception-0.2.6-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.7":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.7/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.7","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"231253eacbdc4ff966726b1e035e673059c9454462ada1b20fd42ed9db20b625","md5":"e51255b7427f39836a6e85940a00a1ba","sha256":"2777a171995d3ed83208c1eb678c2f155a4e6b02491a889ea4bf7f55b62681c7"},"downloads":-1,"filename":"teleexception-0.2.7-py3-none-any.whl","has_sig":false,"md5_digest":"e51255b7427f39836a6e85940a00a1ba","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9721,"upload_time":"2022-10-30T03:47:44","upload_time_iso_8601":"2022-10-30T03:47:44.763548Z","url":"https://files.pythonhosted.org/packages/23/12/53eacbdc4ff966726b1e035e673059c9454462ada1b20fd42ed9db20b625/teleexception-0.2.7-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.8":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.8/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.8","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"bd861b78e1492bdc516e1673b7147b5a8ed33c5e36fee983b86054929803b65c","md5":"9fdad32e03789b579ba1445fcb5e88e8","sha256":"3fe2ebc3e6b0c18c9ea2693661850460a5605eda80fb7b7534c5134a0de63310"},"downloads":-1,"filename":"teleexception-0.2.8-py3-none-any.whl","has_sig":false,"md5_digest":"9fdad32e03789b579ba1445fcb5e88e8","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9773,"upload_time":"2022-11-01T11:55:55","upload_time_iso_8601":"2022-11-01T11:55:55.901538Z","url":"https://files.pythonhosted.org/packages/bd/86/1b78e1492bdc516e1673b7147b5a8ed33c5e36fee983b86054929803b65c/teleexception-0.2.8-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.2.9":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.2.9/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.2.9","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"07628ab89637f9812abc4e470c04cb8b1da05977c540ae5d6007fa9be9b539a2","md5":"e6958260fbf35f49b31b341557658a42","sha256":"ea5fdac1b4de5311824b57f6d5ae5b1ebce0ce1088f1160315e124d7f85b8df1"},"downloads":-1,"filename":"teleexception-0.2.9-py3-none-any.whl","has_sig":false,"md5_digest":"e6958260fbf35f49b31b341557658a42","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":9774,"upload_time":"2022-11-01T14:18:29","upload_time_iso_8601":"2022-11-01T14:18:29.716587Z","url":"https://files.pythonhosted.org/packages/07/62/8ab89637f9812abc4e470c04cb8b1da05977c540ae5d6007fa9be9b539a2/teleexception-0.2.9-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.0":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.0/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.0","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"8a25785dd41d46b7080ac88ef12f75894723eac5f9bdfc29205853593c1dd021","md5":"3150b1ec80c7fbc1511c78d69020c7cc","sha256":"79bee030e152d7cc0c67484ffc1d8def25dcc4f31c421c120806841ac6e78abe"},"downloads":-1,"filename":"teleexception-0.3.0-py3-none-any.whl","has_sig":false,"md5_digest":"3150b1ec80c7fbc1511c78d69020c7cc","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11768,"upload_time":"2023-01-29T10:52:31","upload_time_iso_8601":"2023-01-29T10:52:31.230899Z","url":"https://files.pythonhosted.org/packages/8a/25/785dd41d46b7080ac88ef12f75894723eac5f9bdfc29205853593c1dd021/teleexception-0.3.0-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.1":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.1/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.1","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"d0dc4e83f8b7d9a76d7b941c7bdad4224b5ba5c9f7432d5fc68ef191f15e37f9","md5":"99da676faf19aa5e1b74ebde2865f666","sha256":"55a47a073a1e5e563e8b585a86b3b9d0cd2846b61d556ad4588957307f527709"},"downloads":-1,"filename":"teleexception-0.3.1-py3-none-any.whl","has_sig":false,"md5_digest":"99da676faf19aa5e1b74ebde2865f666","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11666,"upload_time":"2023-01-29T11:17:29","upload_time_iso_8601":"2023-01-29T11:17:29.483417Z","url":"https://files.pythonhosted.org/packages/d0/dc/4e83f8b7d9a76d7b941c7bdad4224b5ba5c9f7432d5fc68ef191f15e37f9/teleexception-0.3.1-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.10":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.10/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.10","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"239162e28dfefabaeafffadd484c508161520aa270ab33a8999f151bf10074db","md5":"d7927c42a268d359c6b14bee5e90c613","sha256":"e4ea6ae91f3304752805aac9a6f31ac6bb1a94ad8383a451482c5108aa687180"},"downloads":-1,"filename":"teleexception-0.3.10-py3-none-any.whl","has_sig":false,"md5_digest":"d7927c42a268d359c6b14bee5e90c613","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":12721,"upload_time":"2023-02-16T06:49:36","upload_time_iso_8601":"2023-02-16T06:49:36.198561Z","url":"https://files.pythonhosted.org/packages/23/91/62e28dfefabaeafffadd484c508161520aa270ab33a8999f151bf10074db/teleexception-0.3.10-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.11":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.11/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.11","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"b03a24f8c3e0cea271481393e18aeaf9effb49a29240031c1ed15a7fdfdbbf62","md5":"fe56c6a729a01bfb88565bdff1a94bee","sha256":"2ec891fc2c51ed110ba526e806e7d2138b200d8981b066128956a49a5c82ad64"},"downloads":-1,"filename":"teleexception-0.3.11-py3-none-any.whl","has_sig":false,"md5_digest":"fe56c6a729a01bfb88565bdff1a94bee","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":12763,"upload_time":"2023-03-06T11:30:20","upload_time_iso_8601":"2023-03-06T11:30:20.257463Z","url":"https://files.pythonhosted.org/packages/b0/3a/24f8c3e0cea271481393e18aeaf9effb49a29240031c1ed15a7fdfdbbf62/teleexception-0.3.11-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.12":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.12/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.12","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"4f6882733ea5da0c72b5a344456eeedf5b593173399b353baa44779c5dad1700","md5":"0e99146aea83a9153cbaf6d41c7fe268","sha256":"ca2cd9680358b1c1c9ce790055535dd4eb6507aaf7f063cf466967581301bdde"},"downloads":-1,"filename":"teleexception-0.3.12-py3-none-any.whl","has_sig":false,"md5_digest":"0e99146aea83a9153cbaf6d41c7fe268","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":12818,"upload_time":"2023-03-16T13:14:42","upload_time_iso_8601":"2023-03-16T13:14:42.148056Z","url":"https://files.pythonhosted.org/packages/4f/68/82733ea5da0c72b5a344456eeedf5b593173399b353baa44779c5dad1700/teleexception-0.3.12-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.13":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.13/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.13","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"fbef39424929c809d22b33aad0cb2bc76ec3adaa76ff80949e6d4330b59e02fe","md5":"a97bc8821ed364ddbc999cfc9fac8684","sha256":"8798fbe2e6e116fbb5662fbdcd8b296b95b2481a2a6b5f324923af6975c5927f"},"downloads":-1,"filename":"teleexception-0.3.13-py3-none-any.whl","has_sig":false,"md5_digest":"a97bc8821ed364ddbc999cfc9fac8684","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13199,"upload_time":"2023-04-25T03:41:54","upload_time_iso_8601":"2023-04-25T03:41:54.369910Z","url":"https://files.pythonhosted.org/packages/fb/ef/39424929c809d22b33aad0cb2bc76ec3adaa76ff80949e6d4330b59e02fe/teleexception-0.3.13-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.14":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.14/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.14","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"17b166265f89122a216523a23c77bd6a355c2c2a6e826bb0fc3718f91901e10f","md5":"afc351165dfa5d8b092e62e263d4b9de","sha256":"6ef490c762e753388230b36d7a902f067af70a0c021257caa40e6ed427da510b"},"downloads":-1,"filename":"teleexception-0.3.14-py3-none-any.whl","has_sig":false,"md5_digest":"afc351165dfa5d8b092e62e263d4b9de","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13199,"upload_time":"2023-04-25T07:29:47","upload_time_iso_8601":"2023-04-25T07:29:47.052916Z","url":"https://files.pythonhosted.org/packages/17/b1/66265f89122a216523a23c77bd6a355c2c2a6e826bb0fc3718f91901e10f/teleexception-0.3.14-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.15":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.15/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.15","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"4bb38ef8fc2bf3e56d90450474b5e761397a06f1b30a984b3b64829312d10eaa","md5":"12ecd88189e56214b0d6df995804c59a","sha256":"57b2749ca8574a41ffa2380745377d4c761353a2dfc014637400418ec1f352ff"},"downloads":-1,"filename":"teleexception-0.3.15-py3-none-any.whl","has_sig":false,"md5_digest":"12ecd88189e56214b0d6df995804c59a","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13500,"upload_time":"2023-05-18T08:18:01","upload_time_iso_8601":"2023-05-18T08:18:01.694452Z","url":"https://files.pythonhosted.org/packages/4b/b3/8ef8fc2bf3e56d90450474b5e761397a06f1b30a984b3b64829312d10eaa/teleexception-0.3.15-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.16":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.16/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.16","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"674547eca8b0ff2fb8ccbc11815c091d7e7fc9b797a9f975ed2856d499a429b4","md5":"5e7ea1a1f85e476244b111da046e06ac","sha256":"0a58893dadf3f268c03bfdc4ef45fe29054f444e900c36d677f65c34d19ac8ff"},"downloads":-1,"filename":"teleexception-0.3.16-py3-none-any.whl","has_sig":false,"md5_digest":"5e7ea1a1f85e476244b111da046e06ac","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13608,"upload_time":"2023-05-22T12:03:47","upload_time_iso_8601":"2023-05-22T12:03:47.503461Z","url":"https://files.pythonhosted.org/packages/67/45/47eca8b0ff2fb8ccbc11815c091d7e7fc9b797a9f975ed2856d499a429b4/teleexception-0.3.16-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.17":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.17/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.17","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"2e14a0fa4fb525cf5f87a7d7c27221ea4112395bfa1f76a45e74124e71b50009","md5":"1add5a61ca06e459daa03737b5748b64","sha256":"b8b775f8a7c1ca9cf1f5ec8e5fe0e6d7bfa6fa71bec2981b060b53312cb82ed7"},"downloads":-1,"filename":"teleexception-0.3.17-py3-none-any.whl","has_sig":false,"md5_digest":"1add5a61ca06e459daa03737b5748b64","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13689,"upload_time":"2023-05-30T11:04:44","upload_time_iso_8601":"2023-05-30T11:04:44.449646Z","url":"https://files.pythonhosted.org/packages/2e/14/a0fa4fb525cf5f87a7d7c27221ea4112395bfa1f76a45e74124e71b50009/teleexception-0.3.17-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.18":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.18/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.18","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"185630cd9dd09c0884db6479410e977e3955df7184fe83e0fc1eb8d215100405","md5":"f4a1a41f3c6fd3e410c06525f3a408af","sha256":"b51302113dc0a1d89df96ae72e52433866b9974198da2b3badc459e4d826db42"},"downloads":-1,"filename":"teleexception-0.3.18-py3-none-any.whl","has_sig":false,"md5_digest":"f4a1a41f3c6fd3e410c06525f3a408af","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13798,"upload_time":"2023-06-02T01:14:05","upload_time_iso_8601":"2023-06-02T01:14:05.374528Z","url":"https://files.pythonhosted.org/packages/18/56/30cd9dd09c0884db6479410e977e3955df7184fe83e0fc1eb8d215100405/teleexception-0.3.18-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.19":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.19/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.19","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"d407c4a15297b66731bdc4f9c83c906fb31847149c407a82fdd4b4b4beb3e394","md5":"12e2b688c80f6a2366299224b12cbc33","sha256":"0a6a8f44f31d6673c45377192889b9ebbdd4a2e0d7b967f2d4d854aa22c8961c"},"downloads":-1,"filename":"teleexception-0.3.19-py3-none-any.whl","has_sig":false,"md5_digest":"12e2b688c80f6a2366299224b12cbc33","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13833,"upload_time":"2023-06-02T01:28:55","upload_time_iso_8601":"2023-06-02T01:28:55.054003Z","url":"https://files.pythonhosted.org/packages/d4/07/c4a15297b66731bdc4f9c83c906fb31847149c407a82fdd4b4b4beb3e394/teleexception-0.3.19-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.2":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.2/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.2","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"6b69ac186856daab298f179cc217d7b3eadec4bad9675bf24ad461cff3a04327","md5":"d45131f2f4b9898cbd4ac0c2075cc919","sha256":"c17a426985981ed2b14f4d7dbda96377959faa81eecfbad11048b5d4c3b09cea"},"downloads":-1,"filename":"teleexception-0.3.2-py3-none-any.whl","has_sig":false,"md5_digest":"d45131f2f4b9898cbd4ac0c2075cc919","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11667,"upload_time":"2023-01-30T01:12:01","upload_time_iso_8601":"2023-01-30T01:12:01.279475Z","url":"https://files.pythonhosted.org/packages/6b/69/ac186856daab298f179cc217d7b3eadec4bad9675bf24ad461cff3a04327/teleexception-0.3.2-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.20":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.20/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.20","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"aa40be1bc23735a0efb60427151c3ad509030122ae8b679c3eecb016f41a447c","md5":"56ad80219fffaeb0ddd92f357fd062bd","sha256":"cfb257b423b87b0cb9de6d821dd1b9822948e1ee97320ac3fa584be11543d50c"},"downloads":-1,"filename":"teleexception-0.3.20-py3-none-any.whl","has_sig":false,"md5_digest":"56ad80219fffaeb0ddd92f357fd062bd","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":13942,"upload_time":"2023-07-17T06:16:48","upload_time_iso_8601":"2023-07-17T06:16:48.807636Z","url":"https://files.pythonhosted.org/packages/aa/40/be1bc23735a0efb60427151c3ad509030122ae8b679c3eecb016f41a447c/teleexception-0.3.20-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.21":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.21/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.21","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"acb451911fa5b62206af00d4ccb62f2a7d03b2233edb2862e583c46f5931d21a","md5":"56a601f92eb63910c45d97398410da15","sha256":"dd9e4f2f2014eaf66a4323bddafd86058cea084f7932899e7b4ddc1634dad4b9"},"downloads":-1,"filename":"teleexception-0.3.21-py3-none-any.whl","has_sig":false,"md5_digest":"56a601f92eb63910c45d97398410da15","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":14257,"upload_time":"2023-08-23T01:30:20","upload_time_iso_8601":"2023-08-23T01:30:20.158179Z","url":"https://files.pythonhosted.org/packages/ac/b4/51911fa5b62206af00d4ccb62f2a7d03b2233edb2862e583c46f5931d21a/teleexception-0.3.21-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.22":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.22/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.22","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"56ae02358beb454eefe28f5b54a321bf7936d7c53126bb0a24d8f01fdcad9cb4","md5":"937f1cb20e8e320e8284b098138c34b5","sha256":"0c12bcf2329c00660696c8261ea331b4b1dd54cf0b2d5e9b06b6464546fe73f5"},"downloads":-1,"filename":"teleexception-0.3.22-py3-none-any.whl","has_sig":false,"md5_digest":"937f1cb20e8e320e8284b098138c34b5","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":14302,"upload_time":"2023-09-20T08:31:30","upload_time_iso_8601":"2023-09-20T08:31:30.474309Z","url":"https://files.pythonhosted.org/packages/56/ae/02358beb454eefe28f5b54a321bf7936d7c53126bb0a24d8f01fdcad9cb4/teleexception-0.3.22-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.23":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.23/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.23","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"d621a0699cfcc781ddefd7d7baf84525c0d0f8d19cc2593b99f00804685b5fb5","md5":"d90a98eec02f7e16ec2b25ab21d42a37","sha256":"7d69ce364a00fa7dd0756de7142948233cc97aca269e4d2abbd566c834ff0fe1"},"downloads":-1,"filename":"teleexception-0.3.23-py3-none-any.whl","has_sig":false,"md5_digest":"d90a98eec02f7e16ec2b25ab21d42a37","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":14315,"upload_time":"2023-10-22T06:41:07","upload_time_iso_8601":"2023-10-22T06:41:07.175499Z","url":"https://files.pythonhosted.org/packages/d6/21/a0699cfcc781ddefd7d7baf84525c0d0f8d19cc2593b99f00804685b5fb5/teleexception-0.3.23-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.24":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.24/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.24","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"3bd359bd7700c6a9aa4c62b9d3bb0838ef3cadb3b0021d4847aee741b0676d32","md5":"b230b6fda5b1cb723612af618cf37da1","sha256":"5557cf35836437bfcd837528355f1558711e1d78fa5bbeb6daf3bdf0d564ffbf"},"downloads":-1,"filename":"teleexception-0.3.24-py3-none-any.whl","has_sig":false,"md5_digest":"b230b6fda5b1cb723612af618cf37da1","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":15789,"upload_time":"2023-10-24T02:47:57","upload_time_iso_8601":"2023-10-24T02:47:57.284770Z","url":"https://files.pythonhosted.org/packages/3b/d3/59bd7700c6a9aa4c62b9d3bb0838ef3cadb3b0021d4847aee741b0676d32/teleexception-0.3.24-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.25":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.25/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.25","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"cbf6f040259387ab68bd273c5d23bcacee31e7a7931f83d45b757d48efb7b6da","md5":"042e7af520037a63005840c6fd26a505","sha256":"f50119e089458d8f911c432d411a0bbf6c5fa2c0ed922a3c6af5b362cfd7626c"},"downloads":-1,"filename":"teleexception-0.3.25-py3-none-any.whl","has_sig":false,"md5_digest":"042e7af520037a63005840c6fd26a505","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":16258,"upload_time":"2023-10-24T03:25:28","upload_time_iso_8601":"2023-10-24T03:25:28.978550Z","url":"https://files.pythonhosted.org/packages/cb/f6/f040259387ab68bd273c5d23bcacee31e7a7931f83d45b757d48efb7b6da/teleexception-0.3.25-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.26":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.26/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.26","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"94b0ec4625c5f9f2b59eb853c12b6764ec79dbf4520db4b130c06fe6cd1cffee","md5":"2068709b1a4fb123878f735f7061340a","sha256":"7fdd539ca385cbb8fdea5d469674bffa213ecf465d8e47606d9a3879c18f530f"},"downloads":-1,"filename":"teleexception-0.3.26-py3-none-any.whl","has_sig":false,"md5_digest":"2068709b1a4fb123878f735f7061340a","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":16247,"upload_time":"2023-10-27T12:43:38","upload_time_iso_8601":"2023-10-27T12:43:38.035756Z","url":"https://files.pythonhosted.org/packages/94/b0/ec4625c5f9f2b59eb853c12b6764ec79dbf4520db4b130c06fe6cd1cffee/teleexception-0.3.26-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.27":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.27/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.27","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"a0be356920dfae06801b2de08855632da601385dc66c678c9ba7faf813dbea66","md5":"fb7cb21ece578a24859ee18525c6b063","sha256":"26c17c1bc1e14bad6435c733bcd7abbca99f2befcc3ded986b949d6a934cea0e"},"downloads":-1,"filename":"teleexception-0.3.27-py3-none-any.whl","has_sig":false,"md5_digest":"fb7cb21ece578a24859ee18525c6b063","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":16543,"upload_time":"2023-11-10T04:07:54","upload_time_iso_8601":"2023-11-10T04:07:54.835018Z","url":"https://files.pythonhosted.org/packages/a0/be/356920dfae06801b2de08855632da601385dc66c678c9ba7faf813dbea66/teleexception-0.3.27-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.28":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.28/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.28","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"21910e2826c3f5474e6df768ec2be9573a8b18dc47d9d66a2028d8649b0bf30a","md5":"7340916e7c19e2825a52832eafc40724","sha256":"3e854b326f620b9a68d1d64245151ed65220a3d119944b13139c59d3698db433"},"downloads":-1,"filename":"teleexception-0.3.28-py3-none-any.whl","has_sig":false,"md5_digest":"7340916e7c19e2825a52832eafc40724","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":16925,"upload_time":"2023-11-18T15:32:53","upload_time_iso_8601":"2023-11-18T15:32:53.866152Z","url":"https://files.pythonhosted.org/packages/21/91/0e2826c3f5474e6df768ec2be9573a8b18dc47d9d66a2028d8649b0bf30a/teleexception-0.3.28-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.29":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.29/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.29","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"ce1fd4bed23684f0a9ffdecd2532ebb9a2a2e1656999e9730bb1862c4f52de1e","md5":"0aa30adffaa526437f5513f1775032db","sha256":"7750df02c5ce7ce22622700c8a6d4c2ab1e22b22dd3b917e338eeb6d4874a564"},"downloads":-1,"filename":"teleexception-0.3.29-py3-none-any.whl","has_sig":false,"md5_digest":"0aa30adffaa526437f5513f1775032db","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":16961,"upload_time":"2023-11-19T16:37:52","upload_time_iso_8601":"2023-11-19T16:37:52.828728Z","url":"https://files.pythonhosted.org/packages/ce/1f/d4bed23684f0a9ffdecd2532ebb9a2a2e1656999e9730bb1862c4f52de1e/teleexception-0.3.29-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.3":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.3/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.3","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"b4f9ab6fdf5c132f29fcae8d7f0a9378688137b1757a4e727d8684ce6edde7f7","md5":"422e5702d8a47800993f76d6854b87ee","sha256":"9d1c50700c650f81392893c14391ebeca55fd5b78e6ebcde78353f252797e3a5"},"downloads":-1,"filename":"teleexception-0.3.3-py3-none-any.whl","has_sig":false,"md5_digest":"422e5702d8a47800993f76d6854b87ee","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11687,"upload_time":"2023-02-03T06:46:11","upload_time_iso_8601":"2023-02-03T06:46:11.974634Z","url":"https://files.pythonhosted.org/packages/b4/f9/ab6fdf5c132f29fcae8d7f0a9378688137b1757a4e727d8684ce6edde7f7/teleexception-0.3.3-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.30":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.30/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.30","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"22173c7f42c26499f039092b55bcf9c519b4c894b66dc5dccd03bd7663788e9f","md5":"63706904ccff3997dbf7f841b76190b7","sha256":"afd38e217b4801b0d93462c649cfb64befbc85f3437ab5944147b9b9558a0ef3"},"downloads":-1,"filename":"teleexception-0.3.30-py3-none-any.whl","has_sig":false,"md5_digest":"63706904ccff3997dbf7f841b76190b7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17180,"upload_time":"2023-12-21T05:24:12","upload_time_iso_8601":"2023-12-21T05:24:12.026449Z","url":"https://files.pythonhosted.org/packages/22/17/3c7f42c26499f039092b55bcf9c519b4c894b66dc5dccd03bd7663788e9f/teleexception-0.3.30-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.31":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.31/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.31","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"253813b2957b07943757e0aaff194de6f49563964c6c439050bcce85e94c877a","md5":"6f2155c39202623131eabbb9d7d93706","sha256":"f0a098e6b8985c57476675d9395bc3690e209ffd9a7eac0d57892546c1c0bd69"},"downloads":-1,"filename":"teleexception-0.3.31-py3-none-any.whl","has_sig":false,"md5_digest":"6f2155c39202623131eabbb9d7d93706","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17247,"upload_time":"2024-01-16T07:22:10","upload_time_iso_8601":"2024-01-16T07:22:10.318379Z","url":"https://files.pythonhosted.org/packages/25/38/13b2957b07943757e0aaff194de6f49563964c6c439050bcce85e94c877a/teleexception-0.3.31-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.32":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.32/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.32","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"45e4934be652fca76c87f5039d8714e5cf81348bcf1a03cba5f133ffb243cac3","md5":"5283771b40c6ff3cedf95429a44b3a59","sha256":"7afe8b82f258f386c1fddbaf1c7ac74381febfb82c389c1ef59379ba061d2e31"},"downloads":-1,"filename":"teleexception-0.3.32-py3-none-any.whl","has_sig":false,"md5_digest":"5283771b40c6ff3cedf95429a44b3a59","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17247,"upload_time":"2024-01-22T02:38:59","upload_time_iso_8601":"2024-01-22T02:38:59.620309Z","url":"https://files.pythonhosted.org/packages/45/e4/934be652fca76c87f5039d8714e5cf81348bcf1a03cba5f133ffb243cac3/teleexception-0.3.32-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.33":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.33/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.33","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"0c8aa8d007ef8938542b914a313b9d6e1206edd36812ecdb6556b15ffa45cb0a","md5":"cbfdd902e71126bc9c38c4b61c95b644","sha256":"8e92ac1abd3f5ecfb02c68be5c5557387fae76c5c0b2128811d33f5fc44eb841"},"downloads":-1,"filename":"teleexception-0.3.33-py3-none-any.whl","has_sig":false,"md5_digest":"cbfdd902e71126bc9c38c4b61c95b644","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17270,"upload_time":"2024-01-26T01:46:10","upload_time_iso_8601":"2024-01-26T01:46:10.096240Z","url":"https://files.pythonhosted.org/packages/0c/8a/a8d007ef8938542b914a313b9d6e1206edd36812ecdb6556b15ffa45cb0a/teleexception-0.3.33-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.34":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.34/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.34","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"f413659b0eeaa452d7e897e522d70aa43b77c7a88f2c20036531f7b6595458c9","md5":"4d72fd94643dbe0779604d8f82270df5","sha256":"98e78050797338c3480916c325c9c6e8fb2d60d01fa2d105ce80ee16891a8a13"},"downloads":-1,"filename":"teleexception-0.3.34-py3-none-any.whl","has_sig":false,"md5_digest":"4d72fd94643dbe0779604d8f82270df5","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17285,"upload_time":"2024-01-29T08:37:36","upload_time_iso_8601":"2024-01-29T08:37:36.247276Z","url":"https://files.pythonhosted.org/packages/f4/13/659b0eeaa452d7e897e522d70aa43b77c7a88f2c20036531f7b6595458c9/teleexception-0.3.34-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.35":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.35/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.35","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"3c65a1d0e566c8b084656a65c9f898e888fca7ac737be637dcf4b289b51165a1","md5":"4a916cc11861e06a334b149d3e938f14","sha256":"b527b1c6dab0e5ddbbc441ba9034be8023e43dd3bf2030aa0cee070efbcc8954"},"downloads":-1,"filename":"teleexception-0.3.35-py3-none-any.whl","has_sig":false,"md5_digest":"4a916cc11861e06a334b149d3e938f14","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17315,"upload_time":"2024-01-31T00:45:18","upload_time_iso_8601":"2024-01-31T00:45:18.848526Z","url":"https://files.pythonhosted.org/packages/3c/65/a1d0e566c8b084656a65c9f898e888fca7ac737be637dcf4b289b51165a1/teleexception-0.3.35-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.36":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.36/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.36","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"9003bbc7ac83609289a32a3f21f8208d157fffbc3a48424d891726e492b04349","md5":"4aaf0b4486cd84bcf450970c4f31b693","sha256":"ed57f5003ccd5d4e3ec5e21c9d4ff34e12e662da8e094fbf478ccdefab013a57"},"downloads":-1,"filename":"teleexception-0.3.36-py3-none-any.whl","has_sig":false,"md5_digest":"4aaf0b4486cd84bcf450970c4f31b693","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17346,"upload_time":"2024-02-05T08:02:43","upload_time_iso_8601":"2024-02-05T08:02:43.164708Z","url":"https://files.pythonhosted.org/packages/90/03/bbc7ac83609289a32a3f21f8208d157fffbc3a48424d891726e492b04349/teleexception-0.3.36-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.37":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.37/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.37","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"08109295706256241791cba5ef683d41768f165ebd5631d269f6103bec39457a","md5":"ec7abae617850b0cf6fa8303b986fc5a","sha256":"54281e3c143fdf64990d0f3728f5be7eb6c0c7892ffb6548332ab3c4928a1fcd"},"downloads":-1,"filename":"teleexception-0.3.37-py3-none-any.whl","has_sig":false,"md5_digest":"ec7abae617850b0cf6fa8303b986fc5a","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17377,"upload_time":"2024-02-18T06:09:54","upload_time_iso_8601":"2024-02-18T06:09:54.962377Z","url":"https://files.pythonhosted.org/packages/08/10/9295706256241791cba5ef683d41768f165ebd5631d269f6103bec39457a/teleexception-0.3.37-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.38":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.38/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.38","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"3e3547c2d56f3107b262e30eb0ee45cc682e62f588dc300f43b5ca8b4bffecbd","md5":"b9ea5a2b0b6109e5a5ad6e7d4d9c4f06","sha256":"625101ba0f08e15bd08ec51ec790ca0ad57599d337dc62b1cafca4ef18aa9fef"},"downloads":-1,"filename":"teleexception-0.3.38-py3-none-any.whl","has_sig":false,"md5_digest":"b9ea5a2b0b6109e5a5ad6e7d4d9c4f06","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17425,"upload_time":"2024-02-21T06:25:36","upload_time_iso_8601":"2024-02-21T06:25:36.778727Z","url":"https://files.pythonhosted.org/packages/3e/35/47c2d56f3107b262e30eb0ee45cc682e62f588dc300f43b5ca8b4bffecbd/teleexception-0.3.38-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.39":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.39/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.39","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"7f981f8455f3c13729d2900d7ad2ee39aa60948a04678f20f28979ac520fef60","md5":"77cb351e3982124dc89f060928793dc9","sha256":"f443db4090c27fb56c6a23efd4c3e3a9bb9e24603edee664405fbad45732bd50"},"downloads":-1,"filename":"teleexception-0.3.39-py3-none-any.whl","has_sig":false,"md5_digest":"77cb351e3982124dc89f060928793dc9","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17479,"upload_time":"2024-02-22T08:07:24","upload_time_iso_8601":"2024-02-22T08:07:24.481158Z","url":"https://files.pythonhosted.org/packages/7f/98/1f8455f3c13729d2900d7ad2ee39aa60948a04678f20f28979ac520fef60/teleexception-0.3.39-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.4":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.4/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.4","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"234725cc5461c34c7421108a7600310ed0696db2e034097ae1735ae50462e3a4","md5":"3c2f2fc90bfb5f2514cb49ebafa68243","sha256":"0784fb5199ef0e89730db00b59a5cf3f6c9a694d9c37cc2b8b3ec6c4668082f5"},"downloads":-1,"filename":"teleexception-0.3.4-py3-none-any.whl","has_sig":false,"md5_digest":"3c2f2fc90bfb5f2514cb49ebafa68243","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11709,"upload_time":"2023-02-03T06:51:24","upload_time_iso_8601":"2023-02-03T06:51:24.078626Z","url":"https://files.pythonhosted.org/packages/23/47/25cc5461c34c7421108a7600310ed0696db2e034097ae1735ae50462e3a4/teleexception-0.3.4-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.40":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.40/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.40","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"67d87e666b6716e231f82e4ab95c07be444267fcc0459613d34c2faf4db61e50","md5":"6a78cc31331f33704867f1fb5eb39e07","sha256":"ea13bae9786aeb186bd1ade6d28faff08558dc7770bb2a349f9c39d641a62e2c"},"downloads":-1,"filename":"teleexception-0.3.40-py3-none-any.whl","has_sig":false,"md5_digest":"6a78cc31331f33704867f1fb5eb39e07","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17489,"upload_time":"2024-02-27T03:05:42","upload_time_iso_8601":"2024-02-27T03:05:42.738798Z","url":"https://files.pythonhosted.org/packages/67/d8/7e666b6716e231f82e4ab95c07be444267fcc0459613d34c2faf4db61e50/teleexception-0.3.40-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.41":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.41/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.41","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"586c6df7dba34fe9572f2153f7c695e4e926b18459981834f31167227c60c460","md5":"bdf03339405dcfe947fdc5777a92a32c","sha256":"4a4017ac49a781cd379ea86aa9295d4b2093bb9aaa9456a27030a945bc1f782e"},"downloads":-1,"filename":"teleexception-0.3.41-py3-none-any.whl","has_sig":false,"md5_digest":"bdf03339405dcfe947fdc5777a92a32c","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17628,"upload_time":"2024-03-14T08:01:43","upload_time_iso_8601":"2024-03-14T08:01:43.170381Z","url":"https://files.pythonhosted.org/packages/58/6c/6df7dba34fe9572f2153f7c695e4e926b18459981834f31167227c60c460/teleexception-0.3.41-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.42":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.42/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.42","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"b307e77f98b9d9498b2ed010cccd9d2979de10960b61570fbec864c146008aaa","md5":"be6d17c009caa84f0131c3d192a832b4","sha256":"97b5c50f1981f4132e4d38ff6964de984673de70ca799bc514ccf51ef987d205"},"downloads":-1,"filename":"teleexception-0.3.42-py3-none-any.whl","has_sig":false,"md5_digest":"be6d17c009caa84f0131c3d192a832b4","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":17749,"upload_time":"2024-03-17T15:03:16","upload_time_iso_8601":"2024-03-17T15:03:16.089283Z","url":"https://files.pythonhosted.org/packages/b3/07/e77f98b9d9498b2ed010cccd9d2979de10960b61570fbec864c146008aaa/teleexception-0.3.42-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.43":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"python exception","license":null,"maintainer":null,"maintainer_email":null,"name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.43/","requires_dist":null,"requires_python":">=3.6","summary":"Python Package for tele exception","version":"0.3.43","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"2b8e85fc7d454da44ccad7049e5084f2b5ae57649af1b83a76092b93edd47436","md5":"94f73a1bf6d9b708432061c2f4ad8a06","sha256":"772cb25a50d05e08bcd16ed97bcb588da053c6aa0491af17d443719914b9b223"},"downloads":-1,"filename":"teleexception-0.3.43-py3-none-any.whl","has_sig":false,"md5_digest":"94f73a1bf6d9b708432061c2f4ad8a06","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":17949,"upload_time":"2024-04-18T09:36:21","upload_time_iso_8601":"2024-04-18T09:36:21.466570Z","url":"https://files.pythonhosted.org/packages/2b/8e/85fc7d454da44ccad7049e5084f2b5ae57649af1b83a76092b93edd47436/teleexception-0.3.43-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.44":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"python exception","license":null,"maintainer":null,"maintainer_email":null,"name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.44/","requires_dist":null,"requires_python":">=3.6","summary":"Python Package for tele exception","version":"0.3.44","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"9e087e791e1255d75690082b06593c91463eb221ebd02d63b1d3fd09dfc6cb48","md5":"25891c88190ebf17aef4e1c788e016f5","sha256":"08bf3975a4e4f6032322a1a35be0609a6becfbaac150c8d92d1e285df1096e32"},"downloads":-1,"filename":"teleexception-0.3.44-py3-none-any.whl","has_sig":false,"md5_digest":"25891c88190ebf17aef4e1c788e016f5","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":17985,"upload_time":"2024-06-11T11:35:26","upload_time_iso_8601":"2024-06-11T11:35:26.578543Z","url":"https://files.pythonhosted.org/packages/9e/08/7e791e1255d75690082b06593c91463eb221ebd02d63b1d3fd09dfc6cb48/teleexception-0.3.44-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.45":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"python exception","license":null,"maintainer":null,"maintainer_email":null,"name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.45/","requires_dist":null,"requires_python":">=3.6","summary":"Python Package for tele exception","version":"0.3.45","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"c38b5defa22accba0c20637251af8ff43db7d0de2d90d4a72af91d312ee8701d","md5":"cb2da32f70f1479c4b756fbf107fff24","sha256":"78a715d4938c74bbf27cb3008800ebd31c25f224c7b14712c2d44417fc456671"},"downloads":-1,"filename":"teleexception-0.3.45-py3-none-any.whl","has_sig":false,"md5_digest":"cb2da32f70f1479c4b756fbf107fff24","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":18472,"upload_time":"2024-07-03T08:32:43","upload_time_iso_8601":"2024-07-03T08:32:43.582703Z","url":"https://files.pythonhosted.org/packages/c3/8b/5defa22accba0c20637251af8ff43db7d0de2d90d4a72af91d312ee8701d/teleexception-0.3.45-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.47":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"python exception","license":null,"maintainer":null,"maintainer_email":null,"name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.47/","requires_dist":null,"requires_python":">=3.6","summary":"Python Package for tele exception","version":"0.3.47","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"e851e851e69fdff5977a52f8ff533573ddf1bdd7229d31ba599332d760a47801","md5":"db2f6c9ac861d1fa2f3888c52514c59d","sha256":"33d4f590188510547d8f18d6eb85b22c287fed188c4f4cf99e714ae64f4c8c1d"},"downloads":-1,"filename":"teleexception-0.3.47-py3-none-any.whl","has_sig":false,"md5_digest":"db2f6c9ac861d1fa2f3888c52514c59d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":18531,"upload_time":"2024-08-16T04:00:12","upload_time_iso_8601":"2024-08-16T04:00:12.005862Z","url":"https://files.pythonhosted.org/packages/e8/51/e851e69fdff5977a52f8ff533573ddf1bdd7229d31ba599332d760a47801/teleexception-0.3.47-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.48":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":null,"downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":null,"keywords":"python exception","license":null,"maintainer":null,"maintainer_email":null,"name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.48/","requires_dist":null,"requires_python":">=3.6","summary":"Python Package for tele exception","version":"0.3.48","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"982a3e7a0341bc0b9d59429258c32057ffbe7eaac71b6ecb6e68e6c60c1151a7","md5":"379012a1d475ea7d2fdcb6fec50c38b3","sha256":"8e16ea364c6b948516e76f02d133a55f412621e9e2e76ff1d87426e94a8a0fa4"},"downloads":-1,"filename":"teleexception-0.3.48-py3-none-any.whl","has_sig":false,"md5_digest":"379012a1d475ea7d2fdcb6fec50c38b3","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6","size":18675,"upload_time":"2024-09-24T02:20:37","upload_time_iso_8601":"2024-09-24T02:20:37.562798Z","url":"https://files.pythonhosted.org/packages/98/2a/3e7a0341bc0b9d59429258c32057ffbe7eaac71b6ecb6e68e6c60c1151a7/teleexception-0.3.48-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.5":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.5/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.5","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"33d5c9e7db21f6e22035fabbf600717774c98dfe8156704770b50032630e44d1","md5":"23fa93a44936aebe902360553da843ae","sha256":"2afe9bf021dc6da981320aba865d14370249b0a6ff9066fa2850410ed7a372df"},"downloads":-1,"filename":"teleexception-0.3.5-py3-none-any.whl","has_sig":false,"md5_digest":"23fa93a44936aebe902360553da843ae","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11743,"upload_time":"2023-02-03T07:04:37","upload_time_iso_8601":"2023-02-03T07:04:37.918844Z","url":"https://files.pythonhosted.org/packages/33/d5/c9e7db21f6e22035fabbf600717774c98dfe8156704770b50032630e44d1/teleexception-0.3.5-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.6":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.6/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.6","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"370f47bc88342211272231fc97478a00702c3857beddf4e51c895b1ca9c3e86d","md5":"285c91d472d52239cf88c027153e2ee7","sha256":"dec9ab9c8d56bdc5b9a2ae72301bb7e2e43b5d7601892e920b32ef0a206fe214"},"downloads":-1,"filename":"teleexception-0.3.6-py3-none-any.whl","has_sig":false,"md5_digest":"285c91d472d52239cf88c027153e2ee7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11790,"upload_time":"2023-02-03T07:16:56","upload_time_iso_8601":"2023-02-03T07:16:56.966379Z","url":"https://files.pythonhosted.org/packages/37/0f/47bc88342211272231fc97478a00702c3857beddf4e51c895b1ca9c3e86d/teleexception-0.3.6-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.7":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.7/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.7","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"1f17d38b3a7acd3292668d1299cfdd360dd939935405d057bc6a0c9db4100cf7","md5":"58ea4feccb549893a0b81725a5bfeec3","sha256":"afe8f849885b04cb449214efca0feb30f3925f4779d66b4b024b5303f5524258"},"downloads":-1,"filename":"teleexception-0.3.7-py3-none-any.whl","has_sig":false,"md5_digest":"58ea4feccb549893a0b81725a5bfeec3","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":11844,"upload_time":"2023-02-06T01:30:45","upload_time_iso_8601":"2023-02-06T01:30:45.069826Z","url":"https://files.pythonhosted.org/packages/1f/17/d38b3a7acd3292668d1299cfdd360dd939935405d057bc6a0c9db4100cf7/teleexception-0.3.7-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.8":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.8/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.8","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"40178ee35f505dcb4792a6485ea3e4bd143141e854cc9d3e8c74830498bb5dbd","md5":"e75cc5c3255e7326ca9723214b568c2d","sha256":"728db2b92608f1da9da052d0897e2083e1b016bdd894a1b77d3587154c3c3ed3"},"downloads":-1,"filename":"teleexception-0.3.8-py3-none-any.whl","has_sig":false,"md5_digest":"e75cc5c3255e7326ca9723214b568c2d","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":12562,"upload_time":"2023-02-13T10:53:14","upload_time_iso_8601":"2023-02-13T10:53:14.963363Z","url":"https://files.pythonhosted.org/packages/40/17/8ee35f505dcb4792a6485ea3e4bd143141e854cc9d3e8c74830498bb5dbd/teleexception-0.3.8-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.3.9":{"info":{"author":"imason","author_email":"635761952@qq.com","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"python exception","license":"","maintainer":"","maintainer_email":"","name":"teleexception","package_url":"https://pypi.org/project/teleexception/","platform":null,"project_url":"https://pypi.org/project/teleexception/","project_urls":null,"provides_extra":null,"release_url":"https://pypi.org/project/teleexception/0.3.9/","requires_dist":null,"requires_python":">=3.6,","summary":"Python Package for tele exception","version":"0.3.9","yanked":false,"yanked_reason":null},"last_serial":25163971,"urls":[{"comment_text":"","digests":{"blake2b_256":"774c9cae6e15be1062801c879fe458c4a1a6c818d6bd705c07b06f68a7356afa","md5":"3f0044304cc309b2fde5800c735d5ba7","sha256":"2b5891a09d49a69c046451f3cd971f138e0ea010286a6fb3cf0990ab9464099e"},"downloads":-1,"filename":"teleexception-0.3.9-py3-none-any.whl","has_sig":false,"md5_digest":"3f0044304cc309b2fde5800c735d5ba7","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.6,","size":12713,"upload_time":"2023-02-15T07:33:21","upload_time_iso_8601":"2023-02-15T07:33:21.145624Z","url":"https://files.pythonhosted.org/packages/77/4c/9cae6e15be1062801c879fe458c4a1a6c818d6bd705c07b06f68a7356afa/teleexception-0.3.9-py3-none-any.whl","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}