{"0.0.1":{"info":{"author":"","author_email":"Vaxila Labs <hello@vaxila-labs.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"opentelemetry-exception-ext","package_url":"https://pypi.org/project/opentelemetry-exception-ext/","platform":null,"project_url":"https://pypi.org/project/opentelemetry-exception-ext/","project_urls":{"Bug Tracker":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext/issues","Homepage":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext"},"provides_extra":null,"release_url":"https://pypi.org/project/opentelemetry-exception-ext/0.0.1/","requires_dist":["opentelemetry-sdk~=1.12"],"requires_python":">=3.7","summary":"OpenTelemetry extension for exception","version":"0.0.1","yanked":false,"yanked_reason":null},"last_serial":20099842,"urls":[{"comment_text":"","digests":{"blake2b_256":"830e4c50483b972668876e1b551fe91016b41dd58a223315c9a5703a44b64795","md5":"b2e7f974d130aac6948f8c14512cf583","sha256":"8158145032a463ba5101c590d695c032ae9a7592e0c4b5001106da978cbd50bb"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.1-py3-none-any.whl","has_sig":false,"md5_digest":"b2e7f974d130aac6948f8c14512cf583","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":4461,"upload_time":"2023-10-04T09:39:34","upload_time_iso_8601":"2023-10-04T09:39:34.281204Z","url":"https://files.pythonhosted.org/packages/83/0e/4c50483b972668876e1b551fe91016b41dd58a223315c9a5703a44b64795/opentelemetry_exception_ext-0.0.1-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"8fa431feabbdb1633b12b67be54aadf7c76d437999b2ad049049ca0d602abd8d","md5":"c9a451bd72118715e7b7bf1f96a7057d","sha256":"259a90e42d37692ee937ad95a5c771132fb80d54b2d32c3512ce302cc5e643ee"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.1.tar.gz","has_sig":false,"md5_digest":"c9a451bd72118715e7b7bf1f96a7057d","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":10246,"upload_time":"2023-10-04T09:39:35","upload_time_iso_8601":"2023-10-04T09:39:35.996118Z","url":"https://files.pythonhosted.org/packages/8f/a4/31feabbdb1633b12b67be54aadf7c76d437999b2ad049049ca0d602abd8d/opentelemetry_exception_ext-0.0.1.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.2":{"info":{"author":"","author_email":"Vaxila Labs <hello@vaxila-labs.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"opentelemetry-exception-ext","package_url":"https://pypi.org/project/opentelemetry-exception-ext/","platform":null,"project_url":"https://pypi.org/project/opentelemetry-exception-ext/","project_urls":{"Bug Tracker":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext/issues","Homepage":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext"},"provides_extra":null,"release_url":"https://pypi.org/project/opentelemetry-exception-ext/0.0.2/","requires_dist":["opentelemetry-sdk~=1.12"],"requires_python":">=3.7","summary":"OpenTelemetry extension for exception","version":"0.0.2","yanked":false,"yanked_reason":null},"last_serial":20099842,"urls":[{"comment_text":"","digests":{"blake2b_256":"8ee1eac990e86c1e8c32a18f4a94460173d74d958f32bbc2ab2529cc42440b35","md5":"a29aacd962f3c437d316d862b55a7c23","sha256":"696c480189ed9e181978ea254dba3273dda61f7abbc654ac4606f6aba1deec26"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.2-py3-none-any.whl","has_sig":false,"md5_digest":"a29aacd962f3c437d316d862b55a7c23","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":4633,"upload_time":"2023-10-10T04:10:06","upload_time_iso_8601":"2023-10-10T04:10:06.359490Z","url":"https://files.pythonhosted.org/packages/8e/e1/eac990e86c1e8c32a18f4a94460173d74d958f32bbc2ab2529cc42440b35/opentelemetry_exception_ext-0.0.2-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"a2f26da43608a7d60310d58e7dcbef4befa5d62d16c1ace5b1b8d9f8dec3d4f2","md5":"e8694f63be7082aa2c8a2305f1a666b2","sha256":"576fd2e6c13f247714639d62391913133ca8eb69aebd3f9fdcca097ba79e2fc6"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.2.tar.gz","has_sig":false,"md5_digest":"e8694f63be7082aa2c8a2305f1a666b2","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":10666,"upload_time":"2023-10-10T04:10:08","upload_time_iso_8601":"2023-10-10T04:10:08.158806Z","url":"https://files.pythonhosted.org/packages/a2/f2/6da43608a7d60310d58e7dcbef4befa5d62d16c1ace5b1b8d9f8dec3d4f2/opentelemetry_exception_ext-0.0.2.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.3":{"info":{"author":"","author_email":"Vaxila Labs <hello@vaxila-labs.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"opentelemetry-exception-ext","package_url":"https://pypi.org/project/opentelemetry-exception-ext/","platform":null,"project_url":"https://pypi.org/project/opentelemetry-exception-ext/","project_urls":{"Bug Tracker":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext/issues","Homepage":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext"},"provides_extra":null,"release_url":"https://pypi.org/project/opentelemetry-exception-ext/0.0.3/","requires_dist":["opentelemetry-sdk~=1.12"],"requires_python":">=3.7","summary":"OpenTelemetry extension for exception","version":"0.0.3","yanked":false,"yanked_reason":null},"last_serial":20099842,"urls":[{"comment_text":"","digests":{"blake2b_256":"db68aa015e02bfb1125d28f7ab996809b646efb58823659aa724c8dc6c8ff7f6","md5":"b717eb331e29b7bf635e4173ce255e5b","sha256":"14bd520ccd244c78138775888dbb4dc4cb0035bba4557e9de11e34f7514ec505"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.3-py3-none-any.whl","has_sig":false,"md5_digest":"b717eb331e29b7bf635e4173ce255e5b","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":4633,"upload_time":"2023-10-10T04:28:24","upload_time_iso_8601":"2023-10-10T04:28:24.910060Z","url":"https://files.pythonhosted.org/packages/db/68/aa015e02bfb1125d28f7ab996809b646efb58823659aa724c8dc6c8ff7f6/opentelemetry_exception_ext-0.0.3-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"df195edb6a93c80dae8b13a1d4dcf512d0732803823911be78a3b290984710b5","md5":"0a398660b01343b18c9a98a1c476aa9e","sha256":"c3da77794ceb464ea7694f3c6668825a56d8d5441f68515e093118ab22987803"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.3.tar.gz","has_sig":false,"md5_digest":"0a398660b01343b18c9a98a1c476aa9e","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":5192,"upload_time":"2023-10-10T04:28:26","upload_time_iso_8601":"2023-10-10T04:28:26.538402Z","url":"https://files.pythonhosted.org/packages/df/19/5edb6a93c80dae8b13a1d4dcf512d0732803823911be78a3b290984710b5/opentelemetry_exception_ext-0.0.3.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]},"0.0.4":{"info":{"author":"","author_email":"Vaxila Labs <hello@vaxila-labs.com>","bugtrack_url":null,"classifiers":["License :: OSI Approved :: MIT License","Operating System :: OS Independent","Programming Language :: Python :: 3"],"description_content_type":"text/markdown","docs_url":null,"download_url":"","downloads":{"last_day":-1,"last_month":-1,"last_week":-1},"dynamic":null,"home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"","name":"opentelemetry-exception-ext","package_url":"https://pypi.org/project/opentelemetry-exception-ext/","platform":null,"project_url":"https://pypi.org/project/opentelemetry-exception-ext/","project_urls":{"Bug Tracker":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext/issues","Homepage":"https://github.com/vaxila-labs/python-opentelemetry-exception-ext"},"provides_extra":null,"release_url":"https://pypi.org/project/opentelemetry-exception-ext/0.0.4/","requires_dist":["opentelemetry-sdk~=1.12"],"requires_python":">=3.7","summary":"OpenTelemetry extension for exception","version":"0.0.4","yanked":false,"yanked_reason":null},"last_serial":20099842,"urls":[{"comment_text":"","digests":{"blake2b_256":"bdba1cfb37e4e38196ca5e9afe04ff9db9e90730456026182f7eee1802cf80bb","md5":"35a1108430a3172738f747673db22ab3","sha256":"b94492ab7f69e3883d6ecf25d57ef373e35082ca12039ddfee05e960246adbfa"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.4-py3-none-any.whl","has_sig":false,"md5_digest":"35a1108430a3172738f747673db22ab3","packagetype":"bdist_wheel","python_version":"py3","requires_python":">=3.7","size":4750,"upload_time":"2023-10-10T10:28:14","upload_time_iso_8601":"2023-10-10T10:28:14.007532Z","url":"https://files.pythonhosted.org/packages/bd/ba/1cfb37e4e38196ca5e9afe04ff9db9e90730456026182f7eee1802cf80bb/opentelemetry_exception_ext-0.0.4-py3-none-any.whl","yanked":false,"yanked_reason":null},{"comment_text":"","digests":{"blake2b_256":"7c4b826800fed30de253857209a4d368edf0d43bf2f403be95d100ffcb4d0763","md5":"4025ff7585deb28fb87faeb129920d93","sha256":"651e78f6a1f50e3acb57e5dae278cbda43fb530383d6935a1d7450bfb20baa19"},"downloads":-1,"filename":"opentelemetry_exception_ext-0.0.4.tar.gz","has_sig":false,"md5_digest":"4025ff7585deb28fb87faeb129920d93","packagetype":"sdist","python_version":"source","requires_python":">=3.7","size":5306,"upload_time":"2023-10-10T10:28:15","upload_time_iso_8601":"2023-10-10T10:28:15.339459Z","url":"https://files.pythonhosted.org/packages/7c/4b/826800fed30de253857209a4d368edf0d43bf2f403be95d100ffcb4d0763/opentelemetry_exception_ext-0.0.4.tar.gz","yanked":false,"yanked_reason":null}],"vulnerabilities":[]}}